### ISSUE TITLE
Sentinel file for S3 origin

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1017]
As noted in #1003, we won't implement sentinel file for S3 until the S3 configuration changes are in place. Once that's done, we should add sentinel option for S3 origins.

**Comment by jhiemstrawisc** [comment]
It looks like fix for this should target [this section of code](https://github.com/PelicanPlatform/pelican/blob/72438ca3815b86a009c6d47521ee98e8492c707b/server_utils/origin.go#L655-L670). If we can make it compatible with S3, we should get http compatibility more or less for free.

**Comment by jhiemstrawisc** [comment]
Closed by #1791
