### ISSUE TITLE
Fuzzy Search on Servers/Namespaces

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#1069]
Pelican Service:
- Registry
- Director

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

> is there a good way to query the registry for the registered issuers for a namespace?
> [10:49](https://chtc-uw.slack.com/archives/C0595FP4DN2/p1712591389290589)
> [@Cannon Lock](https://chtc-uw.slack.com/team/U0225Q1RV5K)
 separately, fuzzy search in the pending registrations in the registry UI would be really nice)

**Comment by brianhlin** [comment]
Actually, it looks like fuzzy search works ok but the results are paginated. So if I'm browsing the pending registrations on page 9 and have a narrow enough search, I have to go back to page 1 to see the results.

**Comment by bbockelm** [comment]
Additionally -- there should be two separate tables, one for caches and one for origins.  It doesn't make much sense to combine the two.
