### ISSUE TITLE
Run Origin through Docker on Apple silicon (also with rosetta emulation)

### ISSUE THREAD

**Issue by iperezx** [PelicanPlatform/pelican#1073]
Pelican Version:
_Run `./pelican --version` to get version number._
hub.opensciencegrid.org/pelican_platform/origin:latest

Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [x] Origin
- [ ] Cache
- [ ] Other (please give the detail)

**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
_Steps to reproduce the behavior._

```
docker run -it -p 8444:8444 -p 8443:8443 -v /PATH:/tmp/pelican --name=pelican-origin --platform=linux/amd64 hub.opensciencegrid.org/pelican_platform/origin:latest -v /tmp/pelican:/foo/bar
```

Where PATH is my local path

Error:
```
Initializing run environment for Pelican...
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: scitokens-server:Logging to file /dev/pts/0
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: scitokens-server:OAuth 2 for MyProxy, version 5.4.1 startup on Mon Apr 08 17:24:13 UTC 2024
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: scitokens-server:loading configuration.
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: oa4mp:Error loading authorization configuration. Disabling use of headers
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: oa4mp:ping enabled
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: oa4mp:No claim source configuration found.
Apr 08, 2024 5:24:13 PM edu.uiuc.ncsa.security.core.util.MyLoggingFacade info
INFO: oa4mp:Starting to load LDAP configuration.
No chain present for host cert; trying to derive one
No chain present; will use empty file
Starting Pelican...
Running pelican with arguments: origin -v /tmp/pelican:/foo/bar
rosetta error: failed to open elf at /lib/ld-musl-x86_64.so.1
```
 Without `--platform=linux/amd64` it can't find an arm64 in the registry and switches to linux/amd64 and gives the above error.
 I also get the following Warning:
 ```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Expected behavior**
_A clear and concise description of what you expected to happen._

To serve an origin.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, MacOS]
 - Browser: [e.g. chrome, safari, if the bug relates to any web user interface]

**Additional context**
_Add any other context about the problem here._

**Comment by iperezx** [comment]
hub.opensciencegrid.org/pelican_platform/origin:v7.6.4 works on my end for apple silicon (with and without --platform on).

Thx

**Comment by iperezx** [comment]
Also the README in https://docs.pelicanplatform.org/install/docker#run-pelican-origin-server
is missing the command `serve` after the image.

**Comment by haoming29** [comment]
@iperezx We changed our tagging for `latest` to the correct version yesterday that should be working with Apple silicon. Could you try again? Note that you may need to remove your existing image first.
