### ISSUE TITLE
Render federation contact information in the director UI if they are provided 

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1074]
In #1012, we added the configuration parameter for federation admin to provide their contact information. We want to display such information in the director UI if they are provided (which is the center of a federation). 

Also, let's make an anchor element so that it's relative easy for various docs/error messages to point to the section where the contact information lives

**Comment by CannonLock** [comment]
```
Hi 
[@Haoming Meng](https://chtc-uw.slack.com/team/U05UKKCN0CE)
 / 
[@Cannon Lock](https://chtc-uw.slack.com/team/U0225Q1RV5K)
 - I am on Zoom with someone setting up an origin.  We give the following error message:





[2:56](https://chtc-uw.slack.com/archives/C0595FP4DN2/p1712606196680399)
Federation XRootD server advertise failed: The namespace "/sci-test" requires administrator approval. Please contact the administrators of https://osdf-registry.osg-htc.org/ for more information.
osdf-registry.osg-htc.orgosdf-registry.osg-htc.org
[Pelican Registry](https://osdf-registry.osg-htc.org/)
Software designed to make data distribution easy
[2:57](https://chtc-uw.slack.com/archives/C0595FP4DN2/p1712606244481129)
However, the poor guy has no clue how to contact the administrators of the OSDF....
```

**Comment by CannonLock** [comment]
Current thought is that errors will pop up the snack bar and highlight the UI button that points to the admin report button.

**Comment by haoming29** [comment]
@CannonLock  We have an admin report button?

**Comment by CannonLock** [comment]
@haoming29 Why is this a director only value? Why not put it at the top level so that the registry can have a Support Email as well?

**Comment by haoming29** [comment]
> @haoming29 Why is this a director only value? Can we add the registry as a component an move it to the top level? Maybe `Federation`?

I think the idea is that we want to have a single point of contact for a federation, and the director is the center of the federation. If the registry want to show the contact information, it need to refer to the director for it

**Comment by CannonLock** [comment]
@haoming29 Makes sense, thanks for explaining.
