### ISSUE TITLE
Director test failures reported in the unit tests

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1100]
In the unit tests, I see the following:

> 2024-04-11T14:22:44.5436070Z time="2024-04-11T14:22:22Z" level=debug msg="Cannot verify token:\nCannot verify token with federation issuer:  Token issuer https://Mac-1712844237799.local:49662 does not match the issuer from the federation. Expecting the issuer to be \n"

[Here's the log for full context](https://productionresultssa0.blob.core.windows.net/actions-results/3413692a-29d8-4584-a914-3c6a2f309a09/workflow-job-run-c6e2058c-abcd-54af-9486-ef51f7b26b9b/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-11T14%3A57%3A35Z&sig=4go4Vz9BguoaFOdvFTH5IAb64gfvhR48TNWOUImMyvY%3D&sp=r&spr=https&sr=b&st=2024-04-11T14%3A47%3A30Z&sv=2021-12-02)

The "Expecting the issuer to be " (followed by no issuer) is potentially concerning.  It could be the tests aren't configured for this to be working -- or it might be indicative of something deeper.

**Comment by jhiemstrawisc** [comment]
This is caused when the federation is configured with `Federation.DirectorUrl` and `Federation.RegistryUrl` but without `Federation.DiscoveryUrl`. I get the error message when I set up a local testing federation using that configuration combination. It looks like the fix should be as simple as setting a fallback for the fedUrl in `token/token_verify.go`:
```
/ Checks that the given token was signed by the federation jwk and also checks that the token has the expected scope
func (a AuthCheckImpl) federationIssuerCheck(c *gin.Context, strToken string, expectedScopes []token_scopes.TokenScope, allScopes bool) error {
	fedURL := param.Federation_DiscoveryUrl.GetString()
	token, err := jwt.Parse([]byte(strToken), jwt.WithVerify(false))

	if err != nil {
		return err
	}

	if fedURL != token.Issuer() {
		return errors.New(fmt.Sprintf("Token issuer %s does not match the issuer from the federation. Expecting the issuer to be %s", token.Issuer(), fedURL))
	}
```
