### ISSUE TITLE
Origin registration

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1107]
Now that we've released multi-exports -- and are starting to get more serious about multiple origins per prefix -- it's about time to separate the concept of a "namespace registration" and "origin registration".

I think we should use the same "trick" for origins as caches -- register them by the hostname inside `/origins` (can't recall if we settled on `/cache` or `/caches` as a prefix when registering caches; we should keep both singular or both plural).

- When starting up, the origin should register all its namespaces and itself.
- There should be tooling or a web UI element for the origin registration so the identity-based workflow can be all web-based if needed.  This can be done as part of this issue or #1105.
- Adjustments should be made to the registration UI so there are three clearly separate sections -- prefixes, origins, and caches.

**Comment by haoming29** [comment]
Closes #623 as it's a duplicated issue

**Comment by haoming29** [comment]
@CannonLock  This is not finished yet. Reopening it
