### ISSUE TITLE
Add tool for querying Pelican configuration

### ISSUE THREAD

**Issue by brianhlin** [PelicanPlatform/pelican#1125]
Pelican Service:
- [X] Client
- [ ] Plugin
- [X] Registry
- [X] Director
- [X] Origin
- [X] Cache
- [ ] Other (please give the detail)

**Is your feature request related to a problem? Please describe.**
It's helpful now that Pelican dumps its entire config at startup but it would be useful to directly query Pelican to see what it thinks its running config may be.

**Describe the solution you'd like**
`condor_config_val` is a venerable tool that would be useful to model this tool after. A few features that I use regularly:

1. Query the system for the value of a specific configuration variable
2. Getting a full dump of the configuration, including defaults that have not been overridden by the operator
3. Query the system for the value of a specific configuration variable along with the file that it's defined in (will be especially useful if #1122 is implemented
4. Understanding what files are used in the configuration (especially #1122 is implemented)

**Comment by jhiemstrawisc** [comment]
See #1427 for an updated description of the issue.
