### ISSUE TITLE
Plugin should advertise version and features in HTCondor machine ads

### ISSUE THREAD

**Issue by matyasselmeci** [PelicanPlatform/pelican#1145]
Pelican Service:
- [ ] Client
- [X] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [ ] Cache
- [ ] Other (please give the detail)

HTCondor 23.7.1 is expected to add a feature that will let file transfer plugins advertise arbitrary classad attributes, as described in this ticket: [HTCONDOR-1051](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1051).  OSPool currently advertises the plugin version by hand (in the OSDF_PLUGIN_VERSION and STASH_PLUGIN_VERSION attributes), but it would be nice if the plugin itself did that for us.

In addition, the plugin could advertise the availability of certain features.  For example, the `?recursive=true` feature was added in 7.7.0, so a user wanting to use that feature needs to land on a machine with plugin version >= 7.7.0.  It would be nicer if the user didn't have to remember the specific version and could just put the feature in their requirements.

Strawman example: add this to the output of `condor_stash_plugin -classad`:

```
StartdAttrs = "OsdfPluginVersion, OsdfPluginFeatures"
OsdfPluginVersion = "7.8.0"
OsdfPluginFeatures = "pack, recursive"
```

**Comment by matyasselmeci** [comment]
I tagged this for 7.9.0 since HTCondor 23.7.1 is going to be released in early May, which would not let you test it in time for 7.8.0.

**Comment by brianaydemir** [comment]
@matyasselmeci At the moment, here's what I see:

```
[brian.aydemir@ap40 ~]> condor_status -af PelicanPluginVersion | sort -u
7.10.1
7.10.9
7.11.2
undefined
```

It looks like @joereuss12 added that attribute in #1113.

Is there a less-strawman/more-official example of what you're looking for? I'm guessing it's easy enough to update `cmd/plugin.go`.

**Comment by matyasselmeci** [comment]
We didn't really discuss this feature so I'm not aware of more official examples than what I put in the description.

I think PelicanPluginVersion is enough for now; there hasn't been any demand for matching against features so I'm fine with putting that on hold and closing this ticket.
