### ISSUE TITLE
`TestPurge` fails on GHA macOS runner

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1151]
We recently got very consistent test failure on GHA macOS runner for the `TestPurge` case: https://github.com/PelicanPlatform/pelican/actions/runs/8802684671/job/24159026949?pr=1146

It's very hard to make the test work, which usually requires re-running a bunch of times, so we should really fix the failure.

**Comment by turetske** [comment]
Make the TestPurge for linux only.
