### ISSUE TITLE
Version reported by Pelican doesn't match version tagged in our production containers

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1163]
Pelican Version:
_Run `./pelican --version` to get version number._

Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [ ] Cache
- [X ] Other (please give the detail)

**Describe the bug**
The osdf production container tagged `v7.7.1` reports this on startup:
```
Starting Pelican...
Running osdf with arguments: origin serve
Version: 7.7.2-next
Build Date: 2024-04-10T19:06:08Z
Build Commit: 5a389787f5fad6d00ca7874766aff8b71826b2a6
Built By: goreleaser
```

**To Reproduce**
Run a production container and observe the version

**Expected behavior**
The version reported by pelican should match the version tagged by the container.

**Comment by aowen-uwmad** [comment]
Encountered independently for `v7.7.3`, which reports `v7.7.4-next` inside the container.

**Comment by bbockelm** [comment]
@CannonLock - the collective memory was that this might be a regression and you may have understood the original fix.  Can you take a look?
