### ISSUE TITLE
Test plugin staging

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#118]
Make a unit test for plugin_stage.go, ensuring correct functionality

**Comment by bbockelm** [comment]
Moving this to v7.2.0 in order to load balance the goals for other unit tests for the remainder of v7.1.0.

**Comment by joereuss12** [comment]
This has been in the backlog for a while. I am going to make a `v7.6.0` goal to revisit this `plugin_staging` as well as start playing around with shadow hooks again. It's time to move this forward

**Comment by joereuss12** [comment]
Merging with new ticket #730
