### ISSUE TITLE
"401 : undefined"

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1184]
When creating a new origin with no password set, I get the following if I try to login to the web interface:

<img width="366" alt="image" src="https://github.com/PelicanPlatform/pelican/assets/1093447/c011fb6f-3e6c-4e84-b2cc-ddca1f3ca9cd">

"401 : undefined" -- we need to provide a better error message.

Additionally, in this case, we shouldn't even be asking for an admin password if it hasn't been initialized.

**Comment by CannonLock** [comment]
@bbockelm Any chance I have access to this origin?

**Comment by CannonLock** [comment]
@haoming29 I think this is a bit of a bug with the new redirection rules. If the db is not initialized the login page should redirect to the code page.

**Comment by haoming29** [comment]
> @haoming29 I think this is a bit of a bug with the new redirection rules. If the db is not initialized the login page should redirect to the code page.

If that's the case, #1193 should fix this issue as well.

**Comment by CannonLock** [comment]
Closed by #1233
