### ISSUE TITLE
Panic error for text that is not a recognized flag

### ISSUE THREAD

**Issue by aowen-uwmad** [PelicanPlatform/pelican#1188]
Pelican Version:

Version: 7.7.4
Build Date: 2024-04-26T19:08:43Z
Build Commit: 4ddcca93b4a8b19be4f0254a62fe815b5a27eb31
Built By: goreleaser

Pelican Service:
- [x] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [ ] Cache
- [ ] Other (please give the detail)

**Describe the bug**

Unrecognized text in the `[flags]` position throws a panic error and unhelpful stack trace.

**To Reproduce**

*Only tested for `pelican object copy`.*

Help text shows the usage is `pelican object copy {source ...} {destination} [flags]`. 
But if unrecognized text is provided in the `[flags]` position, throws the error. 

In this example, I've appended `foo` to the end of the validation download command.

```
$ pelican object copy -f https://osg-htc.org /ospool/uc-shared/public/OSG-Staff/validation/test.txt downloaded_test.txt foo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1608fd1]

goroutine 1 [running]:
main.copyMain(0x304f320, {0xc00069a230, 0x3, 0x5})
        /home/runner/work/pelican/pelican/cmd/object_copy.go:194 +0xf11
github.com/spf13/cobra.(*Command).execute(0x304f320, {0xc00069a1e0, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x30529c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
main.Execute()
        /home/runner/work/pelican/pelican/cmd/root.go:88 +0x8f
main.handleCLI({0xc00014e000, 0x8, 0x8})
        /home/runner/work/pelican/pelican/cmd/main.go:65 +0x1cc
main.main()
        /home/runner/work/pelican/pelican/cmd/main.go:34 +0x28
```

**Expected behavior**

A brief error message stating something like `Unrecognized option(s) provided: foo` followed by help text.

**Screenshots**

n/a

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04 on WSL2

**Additional context**

I only tested this behavior for the `pelican object copy`, but you should probably check if other functions behave the same and similarly address it.

**Comment by turetske** [comment]
@aowen-uwmad This wasn't a bad flag issue at all. I was actually a specific issue with giving a non-directory value to object copy. It read your command as doing a copy on two sources (/ospool/uc-shared/public/OSG-Staff/validation/test.txt AND downloaded_test.txt) which we allow and then expected `foo` to be the destination directory. There is an error check for `foo` not being a directory, but it wasn't set up correctly. I'm fixing it, but just clarifying what the actual issue was.
