### ISSUE TITLE
Overhaull Installation page and how other pages refer to install instructions

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1200]
Some goals for this page:

- Reduce some of the redundancy in our tables
- Make it easier to figure out which package to install, and when to use Docker instead
- We should also be more clear about the fact that some of our packages don't come with the entire kit and caboodle (eg .deb doesn't set up xrootd)
- Clearly reference the requirements to work around #916 in our Docker instructions.

**Comment by haoming29** [comment]
The download-card related issues are resolved with https://github.com/PelicanPlatform/docs/pull/23 merged in
