### ISSUE TITLE
Restructure docs pages/headers organization

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1202]
In our docs focus meeting, we sketched out an architecture like:

- About Pelican (expands to show sub pages)
  - Core Concepts
  - Architecture
- Installing Pelican
- Getting Data with Pelican (expands to show sub pages)
  -  Client
  - HTCondor Plugin
- Serving/Federating your Data (expands to show sub pages)
  - Origin (Each origin will be its own expandable section on the same page?)
- Operating a Federation (expands to show sub pages)
  - Registry
  - Director
  - Cache
- Monitoring Servers
  -  Prometheus
  -  Grafana

**Comment by CannonLock** [comment]
@jhiemstrawisc Any reason you assigned me to this ticket? This is going to involve rewriting/creating documentation that I am not familiar with. Are you just looking for guidance on how this structure can be achieved in the sidebar?

**Comment by CannonLock** [comment]
@haoming29 Has effectively executed nesting here: https://github.com/PelicanPlatform/pelican/blob/main/docs/pages/install/_meta.json

What it takes is a folder level `_meta.json` file that denotes the titles of the files. 

https://nextra.site/docs/docs-theme/page-configuration

**Comment by haoming29** [comment]
I can take this item as I have worked on related things

**Comment by jhiemstrawisc** [comment]
Yep, I think Haoming's got this one now. Sorry for any confusion!
