### ISSUE TITLE
Create a "Getting Started" page for "Getting Data," "Federating Data" and "Operating Federation" sections

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1203]
I think "getting started" looks different depending on what you want to do with Pelican, so we should have these split by category.

Each getting started page should:
- Reference core terminology by linking back to the "core concepts" page that we'll be creating
- Reference Pelican installation and cover any other prerequisites for setting up a minimal example
- Cover the simplest setup of that piece of pelican (client, origin, or federation)
- Provide at least one "hello world" test to convince the user they've succeeded in setting it up
- Link to further documentation for more advanced configuration

**Comment by turetske** [comment]
@jhiemstrawisc I'm not seeing a "Core Concepts" page assigned to anyone, yet.

**Comment by jhiemstrawisc** [comment]
That's the federation overview stuff I was going to work on
