### ISSUE TITLE
Switch remaining usage of http.Client to use common transport

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#122]
Hey @joereuss12, there are still a few checks of `TLSSkipVerify` floating around throughout some of the newer code. Can you switch your `getTransport` function to be exported from the pelican package and use the function wherever we're still manually checking for `TLSSkipVerify`? This will allow us to set up testing frameworks more easily and consistently in the future.

**Comment by joereuss12** [comment]
Yup! My bad must have missed that. Should be a relatively simple fix.
