### ISSUE TITLE
Origin registration status API doesn't update

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1229]
Pelican Version:
_Run `./pelican --version` to get version number._

Pelican Service:
- Origin

**Describe the bug**
_A clear and concise description of what the bug is._

The `/origin_ui/exports` API contains origin registration status. The data should reflect if the origin registration is complete. However, even after the admin fixed the issue at the registry, the API still returns the existing status and didn't pull the latest status.

**Comment by jhiemstrawisc** [comment]
One small comment about these issues -- can you remove any parts of the pre-filled issue that you don't populate? That would make it a bit quicker to find which sections have information.
