### ISSUE TITLE
Topology serverAds expire quickly and left a large gap

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1236]
With the latest code, when I was testing something else, I noticed a constant pattern on the director web UI, where the origin/cache list become empty (with only Pelican server left) from time to time. This can be potentially due to the fact that serverAds has 15min life time and we fetch the topology servers per 4.5 min. In worst case, it will take 4.5 minutes before topology server was fetched.

This will cause inconsistency in director's various responses and we should fix it ASAP.

**Comment by bbockelm** [comment]
I'm not following -- if the ads last for up to 15 minutes and are refreshed every 4.5 minutes, wouldn't we need to miss 3 subsequent updates before a server unexpectedly disappears?

**Comment by haoming29** [comment]
> I'm not following -- if the ads last for up to 15 minutes and are refreshed every 4.5 minutes, wouldn't we need to miss 3 subsequent updates before a server unexpectedly disappears?

You are right. Took a closer look at my configuration, I set the expiration time of serverAds to 3min locally. Closing this issue.
