### ISSUE TITLE
Improvements for the director web interface

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1249]
The director landing page is still fairly lackluster -- I think we have more information "under the hood" that we could expose.

Some additional UI elements I'd like to see:

1.  A status indicator for the service, based on the current health test results.  If the cache/origin is in downtime, we should be able to filter on that via checkbox.
2.  Ability to click on the box for a given service and have it expand with information about the service.  This information should include:
   - Service hostname/port.  If it's a Pelican cache, we already include a link to the web interface.  Non-Pelican services shouldn't include a clickable link.
   - The results of latest tests (expanded from the inline information).
   - The namespace(s) that the origin supports.
   - Link to the registration page.
3.  The fuzzy search should include any information about the service, not only the site name.
4. A filter box that we can turn on/off only the pelican services.
5. An indication of how many entries there are in the table.

**Comment by CannonLock** [comment]
@haoming29 I can find most of this information in the apis, can you help me find/confirm the remaining?

- Downtime indicator
- Test Results ( pelican_director_total_ftx_test_runs? )

**Comment by haoming29** [comment]
> @haoming29 I can find most of this information in the apis, can you help me find/confirm the remaining?
> 
> * Downtime indicator
> * Test Results ( pelican_director_total_ftx_test_runs? )

They should be all in the `/api/v1.0/director_ui/servers`

**Comment by haoming29** [comment]
```json
[
  {
    "name": "Test Origin",
    "auth_url": "https://example-origin.com:8443",
    "broker_url": "https://example-origin.com:8447",
    "url": "https://example-origin.com:8443",
    "web_url": "https://example-origin.com:8444",
    "type": "Origin",
    "latitute": 0,
    "longitude": 0,
    "enableWrite": false,
    "enableFallbackRead": false,
    "filtered": false,
    "filteredType": "",
    "status": "Unknown",
    "namespacePrefixes": [
      "/foo",
      "/bar"
    ]
  }
]
```

`Status` is the test result,  `filtered` is the downtime indicator
