### ISSUE TITLE
Explicitly ignore Pelican endpoints in topology

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1258]
As a follow-up to #1250:

Let's say a cache is in both topology and is a Pelican cache.  When everything is working, the director will see both the Pelican server ad and the topology entry and prefer the information from Pelican (the exception being the downtimes - see #1248).

However, if the service goes offline - say, the host crashes - then there is no more Pelican ad and the topology information takes over.  This is bad: it ensures clients are redirected to the cache even when it is down!

I see two options:
1.  Let's add either a `PelicanService: true` label in topology - causing the OSDF endpoints to ignore the service - or perhaps change the service type from `XRootD cache server` to `Pelican cache` (and analogously for `Pelican origin`).
2. Similarly add a label in topology but change the director code to filter out / ignore such entities.

I like (1) for its simplicity but I worry about the other downstream impacts on things that filter on caches (for example, @CannonLock's maps).

**Comment by matyasselmeci** [comment]
Maybe instead of preferring the information from Pelican, the director should throw an error if there is a mismatch?

**Comment by bbockelm** [comment]
In this case, there's no information from Pelican -- the cache is down!

We shouldn't populate from topology if the cache is known to provide a Pelican service.

**Comment by matyasselmeci** [comment]
OK. FWIW I would like to make "Pelican cache/origin" service types anyway so we don't have to override the endpoints every time. I just created https://opensciencegrid.atlassian.net/browse/SOFTWARE-5867 and referenced this ticket as well.

**Comment by matyasselmeci** [comment]
The linked Jira ticket is done and I've changed the service types of known Pelican caches and origins in CHTC to "Pelican cache"/"Pelican origin" instead. These show up in the old OSDF endpoints (such as for Authfile generation and scitokens.cfg generation), but not in the namespaces JSON.

**Comment by matyasselmeci** [comment]
@bbockelm , is there anything more to do on this ticket?
