### ISSUE TITLE
XRootD backend for origin

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1261]
As part of testing the Denver cache (recently converted to Pelican), Fabio noticed that the origin at FNAL is not working.  It turns out FNAL isn't actually running an origin packaged by XRootD but a custom setup (containing no HTTP support) that redirects the cache to a separate XRootD server (also not supporting XRootD).  Thus, it totally breaks when converting the cache to Pelican.

We should add a new backend (alongside POSIX, S3, and generic HTTP) that supports XRootD; we could then point this directly to the upstream FNAL dCache.

From the [XRootD documentation](https://xrootd.slac.stanford.edu/doc/dev56/pss_config.htm), we'd need something like this:

```
pss.origin data.fnal.gov
ofs.osslib libXrdPss.so
```

(but none of the XCache/pfc directives).  The configuration should require a hostname, will only work with non-authenticated origins, and cannot do arbitrary remaps.  That is, we can't do the equivalent of `-v /foo:/bar`; we have to do `-v /foo:/foo`.

Marking as critical as it blocks the full transition of caches.

**Comment by jhiemstrawisc** [comment]
@bbockelm, as I work on this, do you know of an XRootD Origin configuration I can use for testing? Or perhaps FNAL has a public namespace with a few smallish objects I can use? I'm not sure how I'll determine whether I've hit the mark otherwise.

**Comment by bbockelm** [comment]
(Sample file & endpoint were sent to @jhiemstrawisc out-of-band)

**Comment by jhiemstrawisc** [comment]
Closed by #1285
