### ISSUE TITLE
OSDF cache XRootD self-test content mismatch

### ISSUE THREAD

**Issue by williamnswanson** [PelicanPlatform/pelican#1262]
Pelican Version:
osdf-cache v7.8.1 container
sh-4.4# ./osdf --version
Version: 7.8.2-next
Build Date: 2024-05-08T20:10:38Z
Build Commit: d11c32d7c66b5875c30daff40e5a1866d051961a
Built By: goreleaser

Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [x] Cache
- [ ] Other (please give the detail)

**Describe the bug**
XRootD Status in the ITB OSDF cache web UI is : 
> Self-test monitoring cycle failed: self-test failed during download. File is cleaned up at https://itb-osdf-pelican-cache.osdf-dev.chtc.io:8443/pelican/monitoring/self-test-2024-05-10T14:18:13Z.txt: contents of cache self-test file do not match the one uploaded: [84 104 105 115 32 111 98 106 101 99 116 32 119 97 115 32 99 114 101 97 116 101 100 32 98 121 32 116 104 101 32 80 101 108 105 99 97 110 32 100 105 114 101 99 116 111 114 45 116 101 115 116 32 102 117 110 99 116 105 111 110 97 108 105 116 121 46 32 84 101 115 116 32 105 115 32 105 115 115 117 101 100 32 97 116 32 115 101 108 102 45 116 101 115 116 45 50 48 50 52 45 48 53 45 49 48 84 49 52 58 49 56 58 49 51 90 10]

**Expected behavior**
Self-test content should match uploaded version

**Screenshots**
![image](https://github.com/PelicanPlatform/pelican/assets/144060728/dbf0357c-a11e-47f2-b88b-e52ba639a70e)

**Desktop (please complete the following information):**
 - OS: CentOS Stream 8 container image

**Additional context**
This is the ITB osdf pelican cache in Tiger.

**Comment by haoming29** [comment]
Closed by #1280
