### ISSUE TITLE
Add a Registry Page

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1270]
Create a doc page specifically for the registry to include advanced details for serving and administrating registry and information pruned from the `Serving a Federation` page

Should also include information on how to approve Cache/Origin if the registry requires them to have approval.

Information removed from the `Serving a Federation` page

----

### Useful Configurations for the Registry

There are a couple of configuration parameters you could use to customize the behavior of your registry. Here we highlight the ones that are most frequently set for an admin. You may refer to the full set of registry parameters in the [Parameters page](./parameters.mdx#Registry-DbLocation).

#### `Server.UIAdminUsers`

> `Registry.AdminUsers` is deprecated in Pelican `v7.7.0`. Use `Server.UIAdminUsers` instead.

By default, Pelican registry only has one user with admin privilege, which is whoever starts the registry service and initializes the web UI with the admin password.

However, Pelican also allows you to pass a list of CILogon user identities and grant them the admin privilege. This requires you have your CILogon `client_id` and `client_secret` set up. The user identity of each admin user can be found on their https://cilogon.org/ user page, under "User Attributes", `CILogon User Identifier`, which looks something like `http://cilogon.org/serverA/users/123456`. Once you have the identifiers, simply pass them as an array to `Registry.AdminUsers`:

```yaml
Server:
  UIAdminUsers: ["http://cilogon.org/serverA/users/123456"]
```

#### `Registry.RequireOriginApproval`

By default, a Pelican registry allows any origin to join the federation and serve objects (not the case if running in OSDF mode). You can set `Registry.RequireOriginApproval` if you want to review registration details of a new origin before allowing it to join your federation. With `Registry.RequireOriginApproval == true`, a new origin can successfully *register* against your registry, but the director will not be able to direct object requests to the unapproved origin.

A registry admin may edit, review, approve, or deny a new origin registration in your registry Web UI.

#### `Registry.RequireCacheApproval`

Similarly, Pelican by default allows any cache to join the federation. You can set `Registry.RequireCacheApproval` to `true` in order for caches to require approval before they can serve an object.

#### `Registry.RequireKeyChaining`

By default, Pelican requires namespaces requesting registration to possess a key matching any already-registered super/sub namespaces. For example, if a namespace `/foo/bar` is already registered, then registration of `/foo` or `/foo/bar/baz` can only be done using the public key registered to `/foo/bar`.

#### `Registry.Institutions` and `Registry.InstitutionsUrl`

When a user wants to register a namespace In the registry web UI they must specify which institution this namespace is for. This is a list of options you need to provide. To do so you may either feed a list of `name` and `id` pairs of available institutions to register to `Registry.Institutions` or, if you already have a web endpoint to serve such information, you may pass the URL to `Registry.InstitutionsUrl`. Please refer to https://docs.pelicanplatform.org/parameters#Registry-Institutions for details.

**Comment by jhiemstrawisc** [comment]
Closing this, as I think it was completed by the standalone "Registry" page under the "Operating a Federation" index
