### ISSUE TITLE
Change of cache data location may leave dangling cache files

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1278]
In #1191, we changed the cache run location from `/run/pelican/xcache` to `/run/pelican/cache`. If a server upgrades from previous version to 7.8, the original cache location `xcache` is left in dangling state, and requires manual cleanup, and we lost already cached files in the cache.

Do we want to clean up whatever left under `xcache` folder? to save some disk space for the cache server.

**Comment by jhiemstrawisc** [comment]
We ran into this same issue with #1709, but we've decided this is an issue to communicate with integrators, not something for us to change in the code.
