### ISSUE TITLE
Website automatically generates release plan

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1289]
Pelican Service:

- [ x] Other (please give the detail)

**Describe the solution you'd like**

Rather than have whoever is the release manager update the release plan every time (and sometimes forget to do so). The page should automatically get the dates from the milestones in GitHub, if possible.

The pre-release date is the date of the milestone, the release date is a week after.

We tend to keep a running list of 2-3 milestones at a time, so this might mean the page has multiple upcoming releases (which isn't a bad thing).

**Comment by turetske** [comment]
Was accidentally closed via a mistype I think.

**Comment by CannonLock** [comment]
@turetske Nope, just great work from Austin.

https://github.com/PelicanPlatform/PelicanPlatform.github.io/pull/43
