### ISSUE TITLE
Unit tests for the XRootD UDP monitoring

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#129]
XRootD produces a very specific binary format and sequence of packets for transfers that occur, documented extensively here:

https://xrootd.slac.stanford.edu/doc/dev56/xrd_monitoring.htm

For a unit test:

- We could dump these packets as binary files (or as a JSON-formatted list of raw bytes) inside the git repository.
- Use the `go:embed` mechanism to have the packets inside the unit test file
- In the unit test, invoke the processing handlers directly for `xrootd_metrics.go`, and
- Query the global Prometheus gauge to see if the desired values.

Particularly, I'm suspicious the code that does the accounting for different file prefixes is somewhat buggy... the unit test could focus on seeing if it's aggregating the file transfers correctly.

**Comment by haoming29** [comment]
@bbockelm Looking at the code where you update the BytesXfer metric, you assign the `incBy` the difference between the current number and the previous number. This approach may not work, as I saw a pattern in the incoming summary packets like this:

```console
t=0, link.in = 0;
t=1, link.in = 1000; 
t=2, link.in = 0; 
t=3, link.in = 2000;
```

Basically the number fluctuates between 0 and a monotonic-increasing number, which I believe the non-zero value is a cumulated value than a transient value.
https://github.com/PelicanPlatform/pelican/blob/bf553a28938555bd0b5c03ea8cb5be0199a2be22/metrics/xrootd_metrics.go#L630

The current logic will simply add the non-zero value to the previous non-zero value, which gives you:

```console
t=0, BytesXfer.RX =0; 
t=1, BytesXfer.RX =1000; 
t=2, BytesXfer.RX =1000; 
t=3, BytesXfer.RX =3000
```

which I doubt is the correct value for the bytes read and write.
