### ISSUE TITLE
Website Release links are broken

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1290]
Pelican Service:
- [x] Website

When I click on the 'Release' element of the main pelikanplatform page, I get a "404 | This page could not be found". Either link to the release or remove it as a link all together.

When clicking "All Releases" it goes list of release notes, but the page has no direct links to the releases.

**Comment by haoming29** [comment]
Reopen this issue as the links are still broken:
https://pelicanplatform.org/releases/v7.8.9
https://pelicanplatform.org/releases/v7.9.0
https://pelicanplatform.org/releases/v7.9.1

**Comment by CannonLock** [comment]
@haoming29 Build was borked and fix didn't get published. Now it is fixed!
