### ISSUE TITLE
Website should rebuild whenever a new release is published

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1296]
Pelican Service:
- [X] Webstote

**Is your feature request related to a problem? Please describe.**

If there is a new release on the pelican platform GitHub repo, the 'Releases' page doesn't get updated. It only gets updated if a PR is merged into main on the website repo. This means if there isn't a new update to the website, the 'Releases' page could potentially get quite far behind.

**Describe the solution you'd like**
Whenever a Release (not a pre-release) is made, the website rebuilds OR we have a standing job to rebuild the website once a every 24 hours.

**Comment by CannonLock** [comment]
https://github.com/PelicanPlatform/PelicanPlatform.github.io/commit/f24241a1c1302d284b00941658fe74e7729e1edd
