### ISSUE TITLE
Logging.Debug isn't respected as expected.

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1315]
Pelican Version:
Demonstrated in my local main and in the production container sporting `version = v7.8.4-next`

Pelican Service:
All

**Describe the bug**
The following configuration doesn't turn on debug logging:
```
Logging:
  Debug: true
```

To get debug, I still need to configure
```
Debug: true
Logging:
  Debug: true
```
or pass the `-d` flag.

**Expected behavior**
Configuring:
```
Logging:
  Debug: true
```
should set the logging level to debug.

**Comment by joereuss12** [comment]
@jhiemstrawisc the configuration is:
```
Logging:
   Level: debug
```

Do that and see if it will set it for you.

**Comment by joereuss12** [comment]
After talking with @jhiemstrawisc we figured it was configured wrong on his dev environment and no work is needed here, closing the issue
