### ISSUE TITLE
Incorrect param specific doc anchor links

### ISSUE THREAD

**Issue by brianhlin** [PelicanPlatform/pelican#1326]
**Describe the bug**
On the params page, clicking the param specific link icon will give you a link to the section header instead. For example, trying to link `Origin.ScitokensMapSubject` will yield a link to https://docs.pelicanplatform.org/parameters#Origin.

**To Reproduce**

1. Navigate to https://docs.pelicanplatform.org/parameters
2. Click on the link icon for the specific parameter
![param-links](https://github.com/PelicanPlatform/pelican/assets/390105/49e6fd10-7cbf-44d6-9c52-312534eef232)
4. Paste to find the section-level anchor link

**Expected behavior**
You get the anchor link for the specific param

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Browser: Firefox 125.0.03

**Comment by haoming29** [comment]
This is fixed in https://github.com/PelicanPlatform/docs/pull/26 Closing this issue.
