### ISSUE TITLE
Copy paste error in `Origin.Scitokens*` documentation

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1327]
The definitions in `docs/parameters.yaml` for all our `Origin.Scitokens*` config options say something about enabling the builtin issuer daemon, but that's not what these options do.

The definitions for these can be copied from https://github.com/xrootd/xrootd-scitokens, and each should reference that page for more details.

**Comment by bbockelm** [comment]
Note -- the appropriate documentation is here: https://github.com/xrootd/xrootd/tree/master/src/XrdSciTokens (you had dug up an old archive from when the plugin was standalone).

Assigning to @brianaydemir to spread out the 7.12 ticket load a bit.
