### ISSUE TITLE
Make default log level of the Pelican client part of configuration.

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#135]
I noticed while working on progress bars that a lot of the default log levels in Pelican are `log.ErrorLevel`. This makes the user only ever see errors and not info or warnings. Should this be adjusted to `log.InfoLevel` make the logs a little more informative? Or is error level just fine?
@bbockelm what do you think?

Note: If we want log.ErrorLevel then need to revert change in #132

**Comment by bbockelm** [comment]
I'd like to keep the defaults at error level.  A typical CLI should be very quiet unless things are going on.  If there is information that all clients should see, then it should simply be printed out to the terminal (not using the logging subsystem).

THAT SAID: I think it is a reasonable idea to make the default log level a configuration variable.  Currently, with debug being an on/off, if you enable debugging you get a large volume -- I could see users appreciating slightly more verbose logging.
