### ISSUE TITLE
Investigate timeouts in linter action

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#136]
Occasionally, the linter action fails on a merge due to a timeout. For example, this happened when I merged PR #128. It's not a big issue, but it's annoying and it spams my inbox. It looks like the solution might be as simple as bumping the timeout up a bit, but I haven't investigated beyond that.

**Comment by bbockelm** [comment]
The default golang-ci timeout is 1 minute; we up'd it to 2 minutes here:

https://github.com/PelicanPlatform/pelican/blob/main/.golangci.yaml#L5

It looks like the action you mention timed out at 2 minutes.
- Good news: it appears that our custom configuration is working.
- Bad news: it seems 2 minutes is not enough

How about 3 minutes?

**Comment by jhiemstrawisc** [comment]
Closed by PR #138
