### ISSUE TITLE
Better Formatting for HTTP 500 Error Code on Pelican Client

### ISSUE THREAD

**Issue by patrickbrophy** [PelicanPlatform/pelican#1369]
Pelican Version:
Version: 0.0.1-next

Pelican Service:
- [x] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [ ] Cache
- [ ] Other (please give the detail)

**Describe the bug**
There is insufficient logging for when there is an unanticipated HTTP error code such as 500. It seems to print out a struct of some sort but does not format it in an interpretable or meaningful way.

**To Reproduce**
I ran into this issue when I was following the contributor guide found in the `CONTRIBUTE.md` file. I ran into the issue when I ran the following command:
`./pelican object copy -d -f https://osg-htc.org /ospool/uc-shared/public/OSG-Staff/validation/test.txt downloaded-testfile.txt`

**Expected behavior**
Ideally there would logging of the response body of the request and maybe some other info to help debug the problem.

**Screenshots**
<img width="965" alt="Screenshot 2024-06-03 at 3 07 20 PM" src="https://github.com/PelicanPlatform/pelican/assets/29008404/b41ecbe7-2730-4303-be7a-fbaae3f633a7">

**Desktop**
 - OS: MacOS running ARM64 

**Additional context**
- Additionally I was attached to a dev container running locally on my Mac

**Comment by bbockelm** [comment]
Idea: when the response MIME type is `application/json` and parses as a Pelican error struct, then extract the `msg` attribute and incorporate it into the error stack.

**Comment by haoming29** [comment]
@aowen-uwmad This is the issue we discovered the other day that shares the same error pattern as what you mentioned
