### ISSUE TITLE
Record client IP address as a label to Prometheus metrics for xrootd access

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1425]
* Xrootd already reports client IP address in the detailed monitoring packet: https://xrootd.slac.stanford.edu/doc/dev56/xrd_monitoring.htm#_Toc138968517 (see `host` field) and we have parsed this information into `XrdUserId`, which is used as the key for `userids` TTL cache.
* We creates `sessions` user sessions which tells us information about the user
* We associates `sessions` with `transfers` which contains user file accesses
* We listen to specific type of events for updating these three maps and when there's a file close event, we generate a new Prometheus record for file access
* In this ticket, we want to attach the `host` as a new label for access-related metrics, i.e. `xrootd_transfer_readv_segments_count`, `xrootd_transfer_operations_count`, and `xrootd_transfer_bytes`. 
---

* To do this, we first need to pass the `host` information from `XrdUserId` struct to `UserRecord`, which is the struct for values in `sessions`" . We want to add `host` field to the `UserRecord` struct. https://github.com/PelicanPlatform/pelican/blob/25df30c4bec61d0dea04b1db29615448867e7682/metrics/xrootd_metrics.go#L928-L929
* When we are generating a new Prometheus record when the file is closed, we read from the `sessions` map to get the `host`: https://github.com/PelicanPlatform/pelican/blob/25df30c4bec61d0dea04b1db29615448867e7682/metrics/xrootd_metrics.go#L660-L661
* You also want to keep an eye on wherever we update the value for `sessions` and `userids` map to make sure you aren't missing the `host` field.

To reduce the cardinality of this new label, let's do a `/16` subnet mask and record the masked value.

All the updates should be in `xrootd_metrics.go`, for the subnet function, we should put it in the `utils` package.

**Comment by bbockelm** [comment]
I think a /16 is too much for IPv4; let's use /24 instead.

For IPv6, let's use an aggregation at /64.
