### ISSUE TITLE
"condor_config_val" equivalent CLI tool for Pelican

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1427]
Currently, there's no simple way to dump or share the Pelican configuration.  We should add a new sub-command to Pelican, `pelican config`, with the following functionality:

- `pelican config dump`: dump the entire current configuration.  Defaults to `yaml` output but, based on CLI flags, can output to JSON.
- `pelican config inputs`: Prints out the configuration file(s) used as inputs to the configuration.
- `pelican config get <name1> <name2> ... <nameN>`: Prints out all configuration variables and the values matching name1, name2, ....  The matching rules should be based on Unix (case-insensitive) globs on any part of the string.  So, `pelican config get log` would match any config value with `log` in the name.  For config entries that are lists or non-trivial structures, the printed value should be JSON-encoded and single-line.
- `pelican config summary` (`pelican config`, with no sub-command, defaults to `summary`): Prints, in the specified format, settings that differ from the default configuration.

**Comment by jhiemstrawisc** [comment]
This appears to be a repeat of issue #1125, but this issue provides more detail about the expected interface. I'll close the other.

**Comment by bbockelm** [comment]
Additional items / discussion:

- `config get` should match both substring and globs.  So, `config get origin` would match `Logging.Origin.Http` even though, if it was glob-only, it wouldn't match.
- Have a flag (`--component`?) that allows one to narrow-down the relevant config items.
- Have a flag (`--show-deprecated`?) that allows one to show deprecated configuration value; otherwise, do not show them.
- Make sure to sort the resulting output.  Similarly for `--show-hidden`.

Things that would be nice to have -- but could possibly be done as a follow-up:
- A flag to print out the documentation itself.
- A flag to show only non-default values.  Realistically, this would require us to programmatically generate the defaults from the parameters.yaml instead of hardcoding them in a resource.
