### ISSUE TITLE
The director's origin instance does not return proper headers

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#143]
When running an `object copy` command and when the error returned is `Attempt #1: Pelican director did not include mandatory X-Pelican-Namespace header in response` the debug log does not include any headers

**Comment by jhiemstrawisc** [comment]
Closing this issue. The problem was that auto-discovery for the OSDF pointed to an old director (one still written in flask!). All new instances of the director should have this hammered out.
