### ISSUE TITLE
Mitigate viper bug in failing to bind env to nested config

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1446]
Ref: https://github.com/spf13/viper/issues/761

As Fabio reported, when setting the `Server.TLSCACertificateDirectory` config via environment variable, i.e. `PELICAN_SERVER_TLSCACERTIFICATEDIRECTORY=/etc/grid-security/certificates`, the value isn't propagated to xrootd config. This is because we used `viper.Unmarshal` to unmarshal viper configuration to our defined xrootd configuration struct: https://github.com/PelicanPlatform/pelican/blob/b269e79872031b5d7cb02149960b7f3df12ea933/xrootd/xrootd_config.go#L680-L682

However, given the bug in viper, the values of nested fields are lost in unmarshaling. People in the the referred issue proposed a couple of work-around and we should pick one and replace all our instances where we used `viper.Unmarshal`.

**Comment by bbockelm** [comment]
Can you please link the Viper bug to this ticket?
