### ISSUE TITLE
Web override should trump environment variables

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1447]
The web override is a convenient way to update the Pelican configuration.

However, it appears that environment variables trump all other settings -- meaning you hit "save" on the web interface only to find that the server restarts with the prior value (if the configuration was set through an environment variable; there's no indication this happens in the web UI!).

Let's have the order of precedence go:

- File-based configuration.
- Environment-variable configuration.
- Web-override configuration.

Tagging @brianhlin @matyasselmeci @biozit as operators who might have an opinion on this.

**Comment by haoming29** [comment]
Unfortunately, looking at [viper documentation](https://github.com/spf13/viper/tree/v1.19.0?tab=readme-ov-file#why-viper), the precedence was defined internally in viper. The work around I can think of is to iterate over the generated web config file, call `viper.Set()` explicitly for each config to override env values.
