### ISSUE TITLE
Create and test querying the director for available namespaces

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#147]
This is a followup from issue #81 and it's last line, which wasn't included in the unit test created for that issue:

Query the director for an object within the new origin's namespace. Ensure the response includes the newly registered origin.

**Comment by Techming** [comment]
Follow up on this issue and some breakdown of the tasks required:
* Add a new function to return a list of origins the director contains
* Use the newly created function to make a new test

**Comment by Techming** [comment]
Closed with #185 merged.
