### ISSUE TITLE
Populate parameters.yaml

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#148]
This is a follow up to #71. Add more parameters to parameters.yaml and remove direct access to viper.Get* wherever possible.

This may require updating parameter_generator.go if the added parameters don't conform to the current expected format.

**Comment by turetske** [comment]
I'm unsure how many are left, but these are the ones that are set in config.go that aren't documented in parameters.yaml so are probably configurable?

Authfile
MacaroonsKeyFile
IssuerKey
OriginUI.PasswordFile
XrootdMultiuser
MonitoringData
TLSCertFile
DisableHTTPProxy
DisableProxyFallback
MinimumDownloadSpeed
StoppedTransferTimeout
SlowTransferRampupTime
SlowTransferWindow

**Comment by bbockelm** [comment]
@turetske - assigning this one back to you.

That said, it appears a number of these were already taken care of by @jhiemstrawisc as part of other commits.  Please review if anything is still needed (and closing as appropriate).
