### ISSUE TITLE
Correct the view of a Origins Capabilities

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#1484]
FallbackRead: Permits reads directly from Client
PublicRead: Readable without credentials

_Completed:_

_The use of green and yellow clash with existing uses of those colors to indicate failure state. 

Instead lets use shades of grey and iconography to indicate whether or not the values are enabled or not._

**Comment by jhiemstrawisc** [comment]
One thing to note -- FallbackRead has been deprecated for some time now. I think there are a few JSON values you might be grabbing these from that we've had to maintain for compatibility issues, but the actual configuration values for these two should be:
```
FallbackRead --> DirectReads
PublicRead --> PublicReads
```

Also, the other capabilities also have the `s`, e.g. `Listings` not `Listing`

**Comment by jhiemstrawisc** [comment]
@CannonLock, can I bump the priority of this one for the 7.11 release? The mismatch in capability names as they're displayed in the UI and as they're configured caused some confusion earlier today.

**Comment by CannonLock** [comment]
@bbockelm Should have been closed. I updated the UI right away and the PublicReads thing comes naturally with how I generate the UI which effectively prints out all the capabilities without considering the key name.

```
        "capabilities": {
            "PublicRead": false,
            "Read": false,
            "Write": false,
            "Listing": false,
            "FallBackRead": false
        }
```

**Comment by CannonLock** [comment]
https://github.com/PelicanPlatform/pelican/commit/0c6417887e7eee56e9aa1f2fd8dbebdf4c8a1b8a#diff-6782643841ea2774eebf164c15b95780b81fa2ff7b2a1dcce1a525d7253c6378
