### ISSUE TITLE
OAuth2 redirect goes to wrong URL

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1496]
When the origin does OAuth2 authentication, after a successful authentication, the browser should be redirected back to the original URL.

Currently, if you are getting a token:

```
https://tutorial-origin.osdf-dev.chtc.io/api/v1.0/issuer/device?user_code=BF9_743_6DB
```
and aren't logged in, then it redirects you to a login page.  After login, it takes you back to the origin homepage.  Instead, it should take you back to the original URL (https://tutorial-origin.osdf-dev.chtc.io/api/v1.0/issuer/device?user_code=BF9_743_6DB
 in this case).

Since this is pretty apparent in the tutorials we run, I'm marking this as critical.  I don't know if the problem is on the frontend or backend so assigning it to both Haoming and Cannon.

**Comment by CannonLock** [comment]
@haoming29 This will be you. You just need to add the returnUrl query parameter in the api redirect

For example:

`https://ospool-ap2140.chtc.wisc.edu:8444/view/login/?returnURL=%2Fview%2Forigin%2F`
