### ISSUE TITLE
Additional retryable error classifications

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1511]
When diagnosing NRAO failures, observed a few failures that could be re-classified as retryable:

```
failed upload to ap1-origin.facility.path-cc.io:1095: dial tcp 128.105.69.4:1095: connect: connection refused
```

The above could be a sign of a server that is simply offline; however, there's really nothing a user can do besides retry.

All of the below are various symptoms of a network connectivity issue:

```
failed upload to ap1-origin.facility.path-cc.io:1095: read tcp 10.244.205.41:38264->128.105.69.4:1095: read: connection reset by peer
failed upload to ap1-origin.facility.path-cc.io:1095: write tcp 10.244.118.107:35088->128.105.69.4:1095: write: connection reset by peer
failed upload to ap1-origin.facility.path-cc.io:1095: write tcp 10.244.198.205:43902->128.105.69.4:1095: write: broken pipe
```

In this case, it was a server that was restarted.  These are almost always going to be a transient state -- if the server crashed and stays offline, then it should give a "connection refused" on the retry.

**Comment by turetske** [comment]
We decided not to make "connection refused" a returnable error after discussion with Brian.
