### ISSUE TITLE
Gracefully handle GeoIP failures

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1512]
When MaxMind doesn't know where an IP is, it returns `37.751, -97.822` and sets the "accuracy" to 1000KM.  Take as an example the IP 67.58.51.123.

However, we treat the lat/long in this case (a location in Kansas) as the gospel truth.

If the accuracy returned is ever greater than 100KM, then we should:
- Ensure a warning is displayed on both the director and service (cache/origin) web interface.
- Display an admin-only widget in the director's web interface that is the list of the 5 most recent GeoIP lookup failures
- Take accuracy into account in our sorting algorithms.  If either location (server or client) is at the Kansas location (or close enough -- something like `abs(lat - 37.751) + abs(long + 97.822) < 0.1`), then randomly select any cache within the US.
- If the location is *not* in Kansas (I don't know if MaxMind has a generic European location, for example), take the top 5 "nearest" caches and select one at random.

**Comment by haoming29** [comment]
You might want to wait until #1470 is merged in because that one changed a lot for how we do the sorting the GeoIP lookup.
