### ISSUE TITLE
Outputting progress bars when '--recursive' is set takes a disproportionately large amount of time.

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1525]
When running 'pelican object get' with recursive downloads from the terminal, a large amount of time is taken up printing out the progress bars for each object being downloaded.

For example, when piped to a file so that the progress bars aren't being used, a 11.4 MB download in my contain takes 9 seconds. 
In the terminal with the progress bars, it takes 5 minutes.

One quick fix is to disable progress bars when '--recursive' is set. The other is to have a single progress bar solely based on the number of objects, but it could be misleading if the sizes of the objects vary wildly.

Another option might be to only print out progress bars when the size of an object is above a certain threshold (maybe some multiplier of the bytes/s value?)

**Comment by brianaydemir** [comment]
If not-quick fixes are on the table, it might be worth taking inspiration from other programs.

`git clone`'s output is a single line that's updated in-place and includes: number of objects transferred, number of bytes transferred, and the current rate:

```
Receiving objects: 100% (25004/25004), 36.76 MiB | 9.51 MiB/s, done.
```

`rclone`'s output is similar in spirit and includes a line-per-current-transfer-in-progress (configurable, similar to Pelican's Client.WorkerCount). As with `git clone`, everything is updated in-place:

```
Transferred:        2.637 TiB / 2.682 TiB, 98%, 274.161 MiB/s, ETA 2m52s
Errors:                 1 (retrying may help)
Checks:                 1 / 1, 100%
Transferred:       520711 / 530743, 98%
Elapsed time:   3h19m48.8s
Transferring:
 * idx/theta/theta_llc432…000/0000/0000/11fd.bin: 83% /8.338Mi, 0/s, -
 * idx/theta/theta_llc432…000/0000/0000/1287.bin: 87% /10.726Mi, 0/s, -
 * idx/theta/theta_llc432…000/0000/0000/11ee.bin: 89% /8.087Mi, 0/s, -
 * idx/theta/theta_llc432…000/0000/0000/11e3.bin: 45% /13.016Mi, 0/s, -
 * idx/theta/theta_llc432…000/0000/0000/11ef.bin: 89% /7.834Mi, 0/s, -
 * idx/theta/theta_llc432…000/0000/0000/1212.bin: transferring
 * idx/theta/theta_llc432…000/0000/0000/1219.bin:  0% /15.934Ki, 0/s, -
```

The one thing `rclone` doesn't get quite right here is the denominators on the number of bytes and objects to be transferred. In the example above, there's so much work to be done that it started the process copying objects before calculating the denominators (they should be well north of millions of objects and 10s of TiB).
