### ISSUE TITLE
Update reference to param names from string to `param.GetName()`

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1526]
In https://github.com/PelicanPlatform/pelican/pull/1462, we added fully support to use `GetName()` on param members for getting the string name of the parameter. We should do a one-off check to update our current usage to use `GetName()` instead.

**Comment by jhiemstrawisc** [comment]
I think this was largely tacked in #1693, so I'm going to close this as done. If we find more in the future we can create a new issue.
