### ISSUE TITLE
Migrate Grafana Origin dashboard to Origin WebUI

### ISSUE THREAD

**Issue by patrickbrophy** [PelicanPlatform/pelican#1545]
Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [X] Origin
- [ ] Cache
- [ ] Other (please give the detail)

**Is your feature request related to a problem? Please describe.**
Over the course of my fellowship, I developed a Grafana dashboard for the Origin. The plan has been to eventually integrate the visualizations of the Grafana dashboard into the web ui. 

**Describe the solution you'd like**
Take the existing origin grafana dashboard and implement the visualizations in the origin web ui.

**Additional context**
- Here is the link to the Grafana dashboard [template](https://github.com/PelicanPlatform/pelican/blob/main/docs/public/origin-dashboard-template.json)

- Below is a screenshot of the dashboard
![OriginDashboardV3](https://github.com/user-attachments/assets/150781cd-5f40-4acf-a5ea-f7d062a3289a)

**Comment by CannonLock** [comment]
@bbockelm Here is the ticket for the current design. 

@patrickbrophy Do you have something written up about the stats and graph choices? You previously mentioned some questions you wanted to help the administrators answer.

**Comment by patrickbrophy** [comment]
@CannonLock This was the result of the first round of the design. This doc also links to the user study.

https://docs.google.com/document/d/1PL0swjRgT0kn9IJ9sKt6g6tIcv975sRqu08F7kOh4jU/edit
