### ISSUE TITLE
`pelican object put <empty directory> --recursive` hangs

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1557]
Pelican Version:
v7.10.0

Pelican Service:
Client

**Describe the bug**
Brian Aydemir reports that `pelican object put <dir> --recursive` hangs if the directory is empty.

**To Reproduce**
Create an empty directory, and try transferring it via Pelican. The client hangs. Here's the tail of the debug output, and the location it freezes:
```
DEBUG[2024-08-14T16:10:34Z] Created new transfer job, ID 019151a7-c1ff-72cc-a82c-c09db102a4b0 client 019151a7-c1ff-7189-a7e3-c3d71e3b1bb1, for URL pelican://176ce1b2379c:8445/my-origin/test-dir 
DEBUG[2024-08-14T16:10:34Z] Submiting transfer job 019151a7-c1ff-72cc-a82c-c09db102a4b0 
DEBUG[2024-08-14T16:10:34Z] Closing transfer client 019151a7-c1ff-7189-a7e3-c3d71e3b1bb1 
DEBUG[2024-08-14T16:10:34Z] Processing transfer job for URL pelican://176ce1b2379c:8445/my-origin/test-dir 

< nothing else, does not return >
```

**Expected behavior**
Good question -- I suspect the client should detect the empty directory and throw an error.

**Comment by bbockelm** [comment]
Fixed by #1586
