### ISSUE TITLE
Synchronize downtimes from topology - not working for Pelican caches & origins

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1567]
The integration with topology downtimes relies on the fact that the cache normally shows up in the `namespaces.json`.

However, this is _not_ true when the cache is labelled as a Pelican cache.  Accordingly, when a Pelican cache is put into downtime in topology, this information is not propagated into the director.

The authoritative downtime URL is [here](https://topology.opensciencegrid.org/rgdowntime/xml).  An example downtime for a Pelican cache is as follows:

```
<Downtime>
<ID>1885765227</ID>
<ResourceID>958</ResourceID>
<ResourceGroup>
<GroupName>CHTC-OSDF</GroupName>
<GroupID>1359</GroupID>
</ResourceGroup>
<ResourceName>CHTC_STASHCACHE_CACHE</ResourceName>
<ResourceFQDN>sc-cache.chtc.wisc.edu</ResourceFQDN>
<StartTime>Aug 13, 2024 19:15 PM UTC</StartTime>
<EndTime>Sep 13, 2024 19:15 PM UTC</EndTime>
<Class>UNSCHEDULED</Class>
<Severity>Intermittent Outage</Severity>
<CreatedTime>Aug 13, 2024 19:15 PM UTC</CreatedTime>
<UpdateTime>Not Available</UpdateTime>
<Services>
<Service>
<ID>164</ID>
<Name>Pelican cache</Name>
<Description>Pelican cache server</Description>
</Service>
</Services>
<Description>slow</Description>
</Downtime>
```

Note that Pelican origins show up as a different service name (`Pelican origin`).  We need to capture those as well.

Just as with the namespaces, we should periodically query the downtime URL, determine what resources are unavailable, and synchronize with the director's data structures.

**Comment by jhiemstrawisc** [comment]
I think this was closed by #1581
