### ISSUE TITLE
Recursive and sync transfers fail for a single file

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1588]
Pelican Service:
- [x] Client

**Describe the bug**

When running `pelican object sync <namespace path to object>` on a single object, the command fails due to it attempting a PROPFIND on a folder of `<namespace path to object>`, the same occurs with `pelican object get --recursive` on a single object

**Comment by turetske** [comment]
@bbockelm A question as to what we actually want the behavior to be for a single file.

Specifically for the following examples:
```./pelican object sync ./titanic2.csv "pelican://f2302bf7d7d7:8445/my-origin/titanic.csv" ```
versus
```./pelican object sync ./titanic2.csv "pelican://f2302bf7d7d7:8445/my-origin/" ```

I can implement the second case nicely (which then puts the object at "/my-origin/titanic.csv"), but then for the first case it would put the object at "/my-origin/titanic.csv/titanic.csv". Is the solution to assume for syncs and recursive uploads, the remote path will always be a directory? And just accept that there may be some screw ups by users that cause the "<filename>/<filename>" placement when they put the filename they want as the remote?

**Comment by brianaydemir** [comment]
> A question as to what we actually want the behavior to be for a single file.

This question and its answer is exactly why I'd like a `--dry-run` flag (#1610).
