### ISSUE TITLE
Standardize token creation/verification throughout Pelican

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#159]
After starting work on the CLI for creating origin tokens, I realized we're pretty lackadaisical about how we create and verify tokens throughout the code base. We should pick an internal profile and stick to it. Currently, none of the tokens we create conform to either scitokens2 or wlcg.

A part of this should also be a standard profile-aware token verification tool.

**Comment by haoming29** [comment]
The work from #320 should be able to finish the "token create" part of this ticket, and [#405](https://github.com/PelicanPlatform/pelican/issues/405) will finish the generic token verification part of the ticket. However, the "profile-specific" token verification is not part of the scope for these two PRs and thus need to be addressed separately. I'm working on #320 and best case scenario can get this out tomorrow but I won't expect this to show up in 7.3. Given that, do we want to slip over this ticket to 7.4? (I know we already did it once, life is hard... : (  @jhiemstrawisc )

**Comment by jhiemstrawisc** [comment]
Truer words may never have been spoken -- life is indeed hard. Bumping to 7.4
