### ISSUE TITLE
Treat executable named `pelican_plugin` as an HTCondor File Transfer plugin

### ISSUE THREAD

**Issue by matyasselmeci** [PelicanPlatform/pelican#1600]
Pelican Service:
- [ ] Client
- [x] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [ ] Cache
- [ ] Other (please give the detail)

Right now if the pelican executable is named `stash_plugin` or `osdf_plugin` then it supports the HTCondor File Transfer plugin interface -- for example, you can call it with `-classad` to get the plugin information as a classad.

However, if you try to name it `pelican_plugin` and run `pelican_plugin -classad`, you just get an error of `unknown shorthand flag: 'c' in -classad`. For branding purposes, it might be worth also making it behave as an FT plugin if it's called `pelican_plugin`; alternatively, you could have it behave as a plugin if it ends in `_plugin`.

**Comment by turetske** [comment]
I believe that's because it's currently called `pelican_xfer_plugin`. It should be a simple fix.
