### ISSUE TITLE
GeoIP Error Metric

### ISSUE THREAD

**Issue by patrickbrophy** [PelicanPlatform/pelican#1605]
Issues #1548 and #1512 highlight areas for improving GeoIP error handling and failure visualization. After consulting with @bbockelm, we’ve determined that implementing a new Prometheus metric to track GeoIP failures would be ideal. This metric would include several labels:
- `network`, representing the client’s network.
- `source`, indicating whether the error originated from the client or the server.
- `project`, for identifying which project the error relates to.

The overall objective is to generate a ranking of errors by project, allowing for better insight into the frequency and distribution of GeoIP failures.

**Comment by bbockelm** [comment]
@patrickbrophy and I chatted quickly:
- `error_source` is repetitive; let's change it to just `source`.
- Let's propagate the information about the source and project down the call stack in a context object.
