### ISSUE TITLE
Client progress bars take forever to be "deleted" from the terminal's display

### ISSUE THREAD

**Issue by brianaydemir** [PelicanPlatform/pelican#1612]
Pelican Version:
```
Version: 7.10.6
Build Date: 2024-09-23T15:07:30Z
Build Commit: dbbe43caff6395965a01d1488222e2e897fc9085
Built By: goreleaser
```

Pelican Service:
- [x] Client

**Describe the bug**
By default, `pelican object get --recursive` displays one progress bar per object. After all objects have been copied, it appears that the progress bars are "deleted" from the terminal's display. This proceeds at some small number of progress bars per second, which means it takes an inordinate amount of time to complete if a large number of objects were copied. Furthermore, if there are more progress bars than lines in the terminal's display, it can appear as if nothing is happening.

Unlike #1525, the actual copying of the objects proceeds at a reasonable pace.

**To Reproduce**
Run `pelican object get --recursive` on a directory with more objects than there are lines in the terminal.

**Expected behavior**
I do not have a strong opinion, other than that `pelican` should exit relatively soon after it's completed its work.

I would be okay with the progress bars persisting in the terminal's display.

**Desktop (please complete the following information):**
- OS: MacOS

**Screenshots**
4 seconds elapsed between these screenshots.
<img width="1225" alt="Screen Shot 2024-10-02 at 09 15 01" src="https://github.com/user-attachments/assets/a9795d20-6fbf-4e18-b3b3-8b3925b75af5">
<img width="1225" alt="Screen Shot 2024-10-02 at 09 15 06" src="https://github.com/user-attachments/assets/2b2a6216-52a1-41a8-9885-9fc2906e9eb4">

**Comment by brianaydemir** [comment]
This is also an issue with `pelican object sync` and `pelican object put`.

**Comment by brianaydemir** [comment]
There's something quite strange going on with the way `pelican` is writing to the terminal.

My terminal has 36 lines. The directory I'm doing a `object put --recursive` of has 40 files in it.

In the first screenshot below, we can see that the terminal's scrollback buffer is completely empty prior to running `pelican`.

In the second screenshot, based on the window's scrollbar, we can guess that there are maybe 70+ lines in the buffer.

In the third screenshot, taken after `pelican` (finally) exited, I've scrolled back up to see what's in the buffer. All the repeated lines appear to be for the first 4 files that were copied. (And 40 - 36 = 4.)

<img width="1225" alt="Screen Shot 2024-10-02 at 10 15 44" src="https://github.com/user-attachments/assets/49f12b02-12fb-4b55-ae62-d5304a2be004">
<img width="1225" alt="Screen Shot 2024-10-02 at 10 16 00" src="https://github.com/user-attachments/assets/c3842b81-0396-4b5a-af6e-c496dc35c2bc">
<img width="1225" alt="Screen Shot 2024-10-02 at 10 16 35" src="https://github.com/user-attachments/assets/e6db5e89-485e-42f0-911f-f9bd18fcd9da">

**Comment by turetske** [comment]
This might also be related to #1525 as well

**Comment by brianaydemir** [comment]
Another way to observe the curious behavior of how progress bars are being written and updated to the terminal's display is to run `pelican` with `Logging.Level = Debug` and `Client.WorkerCount = 1`, so that there is no interleaving of objects.
