### ISSUE TITLE
`object sync` (and `object get --recursive`) are not idempotent

### ISSUE THREAD

**Issue by brianaydemir** [PelicanPlatform/pelican#1616]
Pelican Version:
```
Build Date: 2024-10-03T20:02:04Z
Build Commit: 816a384070a7b8a61ba8bbc8169f787062080c2b
Built By: goreleaser
```

Pelican Service:
- [x] Client

**Describe the bug**
Running `pelican object sync osdf://prefix/<remote_dir> <local_dir>` behaves differently depending on whether `<local_dir>` exists prior to running the command.

- If `<local_dir>` does not exist, it is created, and objects are created directly beneath it. I.e., `osdf://prefix/<remote_dir>/x` becomes `<local_dir>/x`.

- If `<local_dir>` does exist, then `<local_dir>/<remote_dir>` is created, and that's where objects are created. I.e., `osdf://prefix/<remote_dir>/x` becomes `<local_dir>/<remote_dir>/x`.

One of the naturally-assumed features of a "sync" command is the ability to run it once to copy data and to run it a second time _exactly as is_ to confirm that nothing was missed and the like. Given the behavior above, this is only possible if you start with a `<local_dir>` that already exists — a detail that I would argue is unintuitive and prone to error.

`object get --recursive` has the same behavior.

**To Reproduce**
1. `pelican object sync osdf://prefix/<remote_dir> <local_dir>` when `<local_dir>` does not exist.
2. Assume that all objects are transferred with error.
3. Run the command again, without modification.
4. Observe that every object is copied again because they are each being written to a different location than the second invocation.
5. Run the command again, without modification.
6. Observe that every object is skipped because they are each being written to the same location as the previous invocation.

**Expected behavior**
If I run `pelican object sync <local_dir> osdf://prefix/<remote_dir>`, what happens that is that `<local_dir>/x` becomes `osdf://prefix/<remote_dir>/x`, _always_. By symmetry, I'd expect the same when the arguments are reversed. It should not matter whether `<local_dir>` exists or not prior to running `object sync`.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by bbockelm** [comment]
@brianaydemir - how does this compare to what `cp -r` or `rsync` does for empty-vs-nonexistent directories?

**Comment by brianaydemir** [comment]
`cp -r <src> <dest>`:

- Requires that all-but-the-final component of `<dest>` already exist.
- If `<src>` ends with a trailing `/`, then it behaves identically whether or not the final component of `<dest>` exists.
- If `<src>` does not end with a trailing `/`, then it behaves similarly to `pelican`.

`rsync -avPi <remote_dir> <local_dir>`:

- Requires that all-but-the-final component of `<local_dir>` already exist.
- Behaves identically whether or not the final component of `<local_dir>` already exists.
- What gets created under `<local_dir>` depends on whether `<remote_dir`> ends in a trailing `/`.

`rclone copy --progress <remote_dir> <local_dir>`:

- Will create all the components of `<local_dir>` as needed.
- Behaves identically whether or not the final component of `<local_dir>` already exists.
- Behaves identically whether or not `<remote_dir>` ends in a trailing `/`.

`aws s3 cp --recursive s3://<remote_dir> <local_dir>`:

- Will create all the components of `<local_dir>` as needed.
- Behaves identically whether or not the final component of `<local_dir>` already exists.
- Behaves identically whether or not `<remote_dir>` ends in a trailing `/`.

**Comment by turetske** [comment]
I feel like I should solve this with my single file fix, since they touch the exact same code.
