### ISSUE TITLE
Improve `pelican_director_server_count` metric

### ISSUE THREAD

**Issue by patrickbrophy** [PelicanPlatform/pelican#1636]
After a brief chat with @bbockelm, we talked about updating the `pelican_director_server_count` metric. The first of the these improvements is cardinality. The cardinality is quite large with the `server_lat`, `server_long`, `server_web_url`, and `server_url`. All of these can be removed. We can also change this metric to a gauge to track the amount of currently connected servers to the director. This change is logical with the idea that the amount of servers can change both positively and negatively. The final improvement would be to add the version of the server. This is so we can see when to break backwards compatibility.

**Comment by bbockelm** [comment]
@jhiemstrawisc / @CannonLock - you guys may be interested in watching this issue.

Having the version number in Prometheus for each of our services will allow us to answer questions like "can we drop backward compatibility with caches running version XYZ?"  I plan a follow-up issue to display this information in the director UI.
