### ISSUE TITLE
Add support for a S3 origin

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#169]
Right now, there's no way to expose / configure the S3 backend.  The plugin exists but there's no Origin configuration values that can actually load it (much less configure the keys, etc).

Add support and create an end-to-end integration test with MinIO.

**Comment by jhiemstrawisc** [comment]
I'm pushing this to v7.3 as I'm still working on this with our UCSD collaborators and I don't think we can reasonably squeeze this into v7.2.
