### ISSUE TITLE
Empty Graphs for v7.11.0 component Web UI main pages

### ISSUE THREAD

**Issue by williamnswanson** [PelicanPlatform/pelican#1714]
Pelican Version:
v7.11.0

Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [X] Director
- [X] Origin
- [X] Cache

**Describe the bug**

Transfer Rate and Storage graphs for the Origin / Cache seem to stay empty. 
"Federation Overview" areas also seem like they should content but don't.

**To Reproduce**

Look at Web UI v7.11.0 components

**Expected behavior**

Transfer Rate and Storage graphs should show information on how much data is being transferred.

**Screenshots**

![image (6)](https://github.com/user-attachments/assets/525dc949-6270-4d68-a59c-4b456e9aa40a)
![image (4)](https://github.com/user-attachments/assets/483f7d3d-86a5-4fb6-9550-1595022155ec)
![image (5)](https://github.com/user-attachments/assets/3d1b0fbe-6138-44b7-9d51-eafde4a2f3d4)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by turetske** [comment]
> Closed by #1289

@CannonLock #1289 has nothing to do with this (it's an issue, not a PR) and hasn't actually been resolved. I'm very confused.

**Comment by CannonLock** [comment]
@turetske CP error, I have edited the original tagging.
