### ISSUE TITLE
S3Region not being configured properly

### ISSUE THREAD

**Issue by Saartank** [PelicanPlatform/pelican#1833]
Even after specifying `us-west-2` in the `S3Region` configuration, the logs indicate that **us-east-1** is still being used. This suggests the region setting is not being applied correctly.  

Everything works as expected when I set my MinIO server region to **us-east-1**. More debugging required.

![image](https://github.com/user-attachments/assets/6d5bd8d0-26e2-488e-9dd1-50368ad851dc)

**Comment by jhiemstrawisc** [comment]
Hey @Saartank, can you re-open this as an issue at https://github.com/PelicanPlatform/xrootd-s3-http? I'm pretty confident Pelican handles this correctly, but that it isn't being used properly by the S3 plugin.

**Comment by Saartank** [comment]
Created: https://github.com/PelicanPlatform/xrootd-s3-http/issues/67
