### ISSUE TITLE
Resolve issues with split origin/cache endpoint for director

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#202]
As a temporary work around to interfacing with XRootD, the director was modified before the 7.0.0 release to serve either caches or origins at its default endpoint based on how the director was configured at launch. This was due to a limitation in XRootD that prevents a redirector service (indicated by the `pss.origin` directive) from taking any paths after its domain, making it impossible to point the redirector to `<my-director>/api/v1.0/director/origins`.

The problem is that we now have two director services, one for caches and one for origins, and synchronization between these two is a problem because Pelican only advertises to one.

Off the top of my head, there are two routes that could be taken to resolve this:
- Follow up on the [open issue](https://github.com/xrootd/xrootd/issues/2068) for xrootd to make redirector configuration with a server path doable. This would allow us to nix one of the directors.
- Adjust Pelican so that the federation discovery step can handle a list of director services. Origins should then advertise to each director, and the directors should probably periodically merge their advertisement caches as well.

**Comment by bbockelm** [comment]
I'll add a third option:

Make the default route be based on the incoming Hostname header, meaning one service can serve either, depending on what the client 'thinks' the hostname is.

At some point, we need to think about high availability / redundancy at the director level.  I'd just like avoid doing so right now.

**Comment by jhiemstrawisc** [comment]
@bbockelm Following up on this because of the recent NACK on a PR that was my interpretation of your comment. Can you provide more detail about what you were thinking? My reading of your suggestion was to have the director read the incoming `Host` header and direct based on whether it thought the original request was for an origin vs a cache.

**Comment by bbockelm** [comment]
I think you got the approach right but I want the feature to be explicitly configured.  That is, make the administrator explicitly enable this mode of operation and then explicitly state what hostname header is associated with the operation.  I.e., something like this in the YAML config:

```
Director:
   DefaultResponse: cache
   CacheResponseHostnames: ["cache.example.com"]
   OriginResponseHostnames: ["origin.example.com"]
```

Your current PR looks at the incoming hostname and does some substring searching to guess intent.  It's always better to make intent explicit instead of implicit.
