### ISSUE TITLE
Have director define a minimum supported version of stashcp

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#21]
(This came up during the Collaborations Day meeting for OSG)

We should add a response to the `pelican` client requests in the director to refuse to serve old clients.  This would provide a quite clear error message if there's unexpected version incompatibility.  Currently, the error messages can be extremely confusing when running an old client against the current OSDF.

**Comment by jhiemstrawisc** [comment]
@bbockelm I'm hoping for a bit of clarification. Do we want future clients to send the director their version and have the director decide whether it can appropriately serve that version of the client, with an appropriate error message in the event that it cannot? Or do we want the director to broadcast the minimum client version it can support and have the client decide if it's capable of parsing the director's response?

**Comment by bbockelm** [comment]
I think we want the client to advertise an appropriate `User-Agent` header

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

and then have the director decide if the client is compatible with the director.

In general, it's better to have the intelligence at the central level and keep the client as simple as possible.
