### ISSUE TITLE
Update deprecated goreleaser command in CI and only build single target for CI

### ISSUE THREAD

**Issue by Techming** [PelicanPlatform/pelican#211]
We got this warning from goreleaser in CI that tells us to update `--rm-dist` to `--clean`

```bash
 DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
```

Also, similar to #50, current goreleaser setup in Test will build for all platforms, which is unnecessary if we run CI in different OSs already, so we can add `--single-target` to only build the artifact for the specific platform. To ensure we test build for uncovered OS, i.e. PowerPC, ARM, we keep building everything for Ubuntu runner but OS specific target for Mac and Windows.

**Comment by bbockelm** [comment]
I like the idea of `--single-target`!

However, I would only want to do that on Mac and Windows.  For Ubuntu, I want to keep everything built as there are some platforms (PowerPC, ARM) without any runners.

**Comment by Techming** [comment]
Close with #218 merged
