### ISSUE TITLE
Have pelican client write out debug file into a known location

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#22]
When debugging pelican failures, multiple individuals have commented they stop using the URL-based transfers because they want the debug output.

Instead, the client should look at the `.job.ad` for a well-known attribute that specifies an output file to write into.  I believe (but need to check) that the URL-based transfers are done before CEDAR transfers, meaning that the debug log would be transferred out if written.

**Comment by joereuss12** [comment]
Hi Brian! Just looking into this today. I have a question, do you want me to use some sort of existing job classad to specify where the output file is written or would you like me to create a whole new job classad that would specify this location/file?

**Comment by bbockelm** [comment]
@joereuss12 - is this fixed by any of the recent PRs?  It's not associated with any yet I seem to recall it being done.

**Comment by joereuss12** [comment]
Yes, this should be done. Just wasn't sure if we wanted this to be kept open until it would work completely with condor but we did successfully implement the -l flag to specify an output file and that can also be read in through an environment variable. Do you want me to see if this works with condor before closing this issue or is it completed enough to close it now?
