### ISSUE TITLE
Improve RPM for Pelican

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#246]
The Pelican RPM only ships the `pelican` binary.  More is needed:

1.  Create a `pelican-osdf-compat` sub-RPM that includes symlinks for `stash_plugin`, `osdf`, and `stashcp`.
2. Have the `pelican-osdf-compat` RPM contain an `Obsoletes` statement, indicating it obsoletes all the prior OSDF/stashcp RPMs we've shipped.
3.  Add a `pelican-server` RPM that contains the systemd unit files needed to startup / shutdown Pelican.

I *think* this is all doable via goreleaser (but it may be that we need to break out a handwritten RPM).

**Comment by bbockelm** [comment]
Also from @timtheisen -- we also need to include the condor config file to enable the `stash_plugin`.

**Comment by matyasselmeci** [comment]
Can we split `pelican-server` into a separate issue? I can get `pelican-osdf-compat` done in time for 7.2.0.

**Comment by matyasselmeci** [comment]
For the compat RPM, Goreleaser does not appear to expand templates within `replaces` and `provides` lists - that is, this
```
provides:
- "osdf-client (= {{ .Version }})"
```
does not result in a deb with a Provides of `osdf-client (= 7.1.1)` but with `osdf-client (= {{ .Version }})` which results in a syntax error when installing.  The RPMs are similarly broken; in addition, I can't use the RPM macros either (`osdf-client = %{version}`) is inserted literally.

Either we have to add a step where we generate `.goreleaser.yml` with the correct version coded in, or just say that we provide `osdf-client=7` and call it a day.

**Comment by matyasselmeci** [comment]
I forked off pelican-server to #331 so I'm marking this resolved.
