### ISSUE TITLE
Have webdav directory listing utilize token-based authorization

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#25]
We think, when stashcp does the directory existence test, it uses a library that doesn't leverage the bearer token.  Investigate this issue and, as necessary, add token support.

Alternately, if token support isn't available, rip out this code.

**Comment by bbockelm** [comment]
@matyasselmeci points out this probably also breaks recursive transfers (which increases the priority to fix).

**Comment by turetske** [comment]
Client side code. Interface for listing remote directories. The token isn't being passed to the web-dev library or it's being passed. "list-directory" function. Possibly customize the http headers.

**Comment by turetske** [comment]
@bbockelm Looking into the code, gowebdav doesn't support this. However, there is an open issue for a fix on their repo, how do we feel about me attempting that rather than ripping out the code?

**Comment by bbockelm** [comment]
What's the GH issue you found?  We should at least get that linked to this one.

**Comment by turetske** [comment]
> What's the GH issue you found? We should at least get that linked to this one.

It's linked here: https://github.com/studio-b12/gowebdav/issues/61

 I did look into adding the support to the base web directory, but honestly my token/http knowledge still feels to weak to do so, so instead I'm removing the isDir code and we can fix it later.

**Comment by bbockelm** [comment]
I'm OK with fixing the directory listing / upload on a future ticket.  Will merge the PR momentarily.
