### ISSUE TITLE
Browser text sometimes unreadable in browsers with dark mode enabled

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#251]
I'd consider this pretty low priority, but when I'm using the browser interface in Firefox with dark mode enabled, some of the text in form fields are barely visible (harder to see on my screen than it is in the image). It would be nice if this text could be color-coded dynamically like other text.
![Screenshot 2023-10-19 at 3 19 36 PM](https://github.com/PelicanPlatform/pelican/assets/75916364/bc7e5993-2291-4138-8541-e00dd08d11e7)

**Comment by CannonLock** [comment]
This was bothering me as I worked on it so I fixed it here: #284
