### ISSUE TITLE
Object get/put

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#259]
The `object copy` mode is functionally equivalent to the old `stashcp` client.  However, `copy` mode has to use a few (potentially flawed) heuristics to see if it's a get or a put.

Add two new modes, `object get` and `object put`, that resolve the ambiguities of which side of the file movement is the data federation.

Make sure to add unit tests to check the variants of the federation location specification (see the unit test for `object share` in #257).

**Comment by joereuss12** [comment]
@bbockelm how would you like this to work with backwards compatibility? Are we just assuming that those using the old stashcp client will just be doing an object copy and to make object get/put only really compatible with Pelican/osdf?
