### ISSUE TITLE
Namespace web UI

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#264]
The namespace registry currently works in a "first come, first serve" mode -- anyone registering an unclaimed namespace is allowed to get it.

An actual production deploy will require the origin admin to provide additional information (such as institution name, issuer details -- anything that is in OSG Topology today) and the registry admin to approve.

Extend the registry so:
- The fields to register are taken from the config.  Should be able to specify some types in order to allow value validation.
- The database holds generic key/value pairs associated with the registration (probably a new table?).
- It has a web UI where the form can be filled in.  If need be, the UI can be left to a separate issue (but a RESTful interface is needed).
- Users can view their pending registrations.
- Admins can approve (or edit) registrations.

**Comment by CannonLock** [comment]
@haoming29 Are registry admins determined by Cilogin groups?

**Comment by haoming29** [comment]
> @haoming29 Are registry admins determined by Cilogin groups?

Good question... and I'm honestly not sure. We might want to confirm with @bbockelm
