### ISSUE TITLE
Web UI for the director

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#265]
The director should have a web UI that contains:

- A view of all the attached origins and caches (structured list of caches, client-side filterable)
- The ability to specify an object in the federation and click "download" to download.
   - Based on the director response, this may generate an OAuth2 workflow.

**Comment by haoming29** [comment]
Do we also want to show the health status of origins the director knows? At least it's API-wise ready by the time this is under the way.

**Comment by CannonLock** [comment]
Going to cut this in two parts as it is not possible to download anything via web UI yet as the director does not have the appropriate CORS headers.
