### ISSUE TITLE
After cookie expiration, web accesses are redirected to activation page

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#277]
After the cookie expires, further web accesses are met with a redirect to the activation code page.  However, once the password has already been set, redirects really should go to the login page instead.

**Comment by CannonLock** [comment]
Hmm, that was the case until I merged the login page for 7.2. First thought is the web build did not update.

**Comment by bbockelm** [comment]
We think this was simply a lack of running `make` on my part -- closing.
