### ISSUE TITLE
Add authorization to Prometheus scraping endpoint

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#291]
Right now, if you go to `<server-url>/metrics` for any server, the Prometheus metrics will return even if you don't have any authentication token. We want to protect this endpoint by only allowing authenticated user to access it, although it might be a bit tricky to do so.

1. Issue a token signed by the server and attach it to the header of the Prometheus static scraper
2. Check token authentication at `/metrics` endpoint
3. Might need to come up a way to refresh the token periodically
4. Add regression tests

Note that this will break director's scraping mechanism. Will need a separate PR to allow director to carry a token when scraping origins' metrics.

**Comment by bbockelm** [comment]
I thought @turetske had worked at this previously, no?

**Comment by haoming29** [comment]
> I thought @turetske had worked at this previously, no?

That's for the query engine endpoint at `/api/v1.0/prometheus`. The scraper endpoint is not protected.

**Comment by bbockelm** [comment]
Ah, thanks!  I hadn't caught that subtlety.
