### ISSUE TITLE
Always generate a CA certificate at server's start

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#301]
Looking at the code I'm a bit confusing about the task of this issue so @bbockelm might need to give the details about this issue. Just serve as a placeholder now so that we don't forget.

**Comment by bbockelm** [comment]
Here's the details:
- If location set by `Server.TLSCACertificateFile` _exists_, then the generated host certificate will be self-signed.  Self-signed certificates are not permitted by the scitokens-cpp library, leading to a certain failure.
- If the location set by `Server.TLSCACertificateFile` does _not_ exist when the host certificate is generated, then the CA is generated and the host certificates are generated from that.

So, we should unconditionally create the CA if we need to generate the host certificate (and never use a self-signed host certificate) to avoid failures in the self-test.
