### ISSUE TITLE
Refactor general server_ui code out of origin_ui

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#308]
Due to implementing origin_ui first, there is a lot of origin specific code that actually code be more general. This should be refactored into server_ui instead of origin_ui so it can be used by other servers such as the cache, director, or namespace. Some of the code in cmd/origin_serve is also more general than just origin code.

**Comment by haoming29** [comment]
In #291 I refactored much of the authorization check code in `web_ui` which can be helpful in implementing this issue

**Comment by haoming29** [comment]
This can be very helpful for #264 as it will greatly reduce repetitive logic we would create.

**Comment by haoming29** [comment]
Looks like #355 will be heavily dependent on this PR in order not to generate duplicate code and #355 was marked as part of 7.3.0. @bbockelm Do you think we should prioritize this issue to get #355 unblocked?
