### ISSUE TITLE
Web ui for the pelican cache

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#309]
Create a web_ui for the pelican cache. Currently the web_ui is not spun up for the pelican cache, this should be changed.

-- The periodic advertisement should be moved once this is implemented

**Comment by haoming29** [comment]
I'm a bit confused about "The periodic advertisement should be moved once this is implemented". Where should it be moved to? For Origin, periodic advertisement is a separate function called in `serveOrigin` which I assume would be the same case for cache?
