### ISSUE TITLE
Handle the display of complex configuration types

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#322]
Current config view does not provide a easy interface for viewing the duration type Go objects. When we add the write interface next milestone lets improve this.

**Comment by CannonLock** [comment]
Clearing milestone, will keep in mind for when the config gets a write endpoint.

**Comment by bbockelm** [comment]
Since a write endpoint is critical-path for 7.6.0, I'm adding a milestone back to this issue.

**Comment by bbockelm** [comment]
@CannonLock - what's the status of this one?
