### ISSUE TITLE
Refactor commonly used util code into util package

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#335]
Refactor general utility functions out of specific directories into pelican/util. This is similar to the web_ui refactoring issue, but broader.

There is a bunch of code that shouldn't be specific to certain packages - for example `MakeRequest`, which has since been moved from the namespace-registry package into the utils package.

A read through of the code and a refactor of obvious functions should be done to move other general functions out of specific packages.

**Comment by jhiemstrawisc** [comment]
Linking issue #320 and issue #159 to this.

**Comment by turetske** [comment]
> Linking issue #320 and issue #159 to this.

@jhiemstrawisc I understand #320, but I don't quite understand why #159 gets linked in?

**Comment by haoming29** [comment]
Link issue #447 and #405 here and PR #429 here that closes #405 
We are making progress!

**Comment by jhiemstrawisc** [comment]
More or less this has been accomplished through lots of other PRs. Closing as done.
