### ISSUE TITLE
Automate Central Services CI on Tiger

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#342]
Currently, whenever we generate a new release, I have to modify the container version our production central services use on Tiger. Let's see if we can figure out a way to automate this with a GHA at some point.

**Comment by bbockelm** [comment]
There's a nice helpful guide here:

https://fluxcd.io/flux/guides/image-update/

However, given Matyas has experience here, I assigned the ticket to him.  Mat, please coordinate with Brian Lin on whether you should do this or just mentor @williamnswanson on how to do it.

**Comment by matyasselmeci** [comment]
Do you want to autoupdate production (osg namespace) or do you want to autoupdate testing (osgdev namespace)? We generally set the version we use in production by hand to avoid accidentally deploying something before it's been tested...

**Comment by jhiemstrawisc** [comment]
@matyasselmeci this is a good question. We don't currently have any real ITB set up, so outside of bugs we stumble across during the course of development and our unit tests (we're up over 30% now!), there's no real "testing" being done. Setting up some of this infrastructure and establishing best practices (eg how do we test before we're confident something is reliable) is one of the topics I'd like us to talk about in the meeting we have planned.

As for right now, whenever we cut a new release, I pretty much immediately update the image version to match.

**Comment by jhiemstrawisc** [comment]
I think we've seen from @williamnswanson that this process probably shouldn't be automated for quite awhile, given the number of nuanced issues we find with each update. I'm going to close this issue and we can revisit when things are a bit more stable.
