### ISSUE TITLE
Placeholder namespace UI

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#354]
In #264, we have a goal of putting together an initial web workflow for the registry for the v7.4.0 milestone.  However, I don't want to wait until next month to get working on it - it's too large for a single issue.

To prepare for the v7.4.0 functionality, let's create a simple, minimally-functional UI for the registry in v7.3.0.  The UI should:
1.  Come up to a splash page a-la the origin.
2. List the registered origins in a table.  Should be at least three columns -- the registered piece of the namespace, the related identity/owner (if any), and a link to download the JWKS.
3. List the caches in a table.

For now, let's hold off on authentication as a separate issue.

@haoming29 ☝️

**Comment by haoming29** [comment]
Also assigned to myself to provide related APIs for the requirement above.

**Comment by CannonLock** [comment]
There are existing APIs up for this that we can start on right away
