### ISSUE TITLE
Implement Metalink for origin redirects in director

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#357]
Right now, when we request a cache from the director, we get back a metalink-conformant list with ranked priority. However, when we request an origin, we get only whichever happens to be first in the ttlcache.

We should make the origin redirects more like the cache redirects to account for the fact that there might be multiple origins corresponding to a namespace (as is the case, for example, with `/chtc/PUBLIC`)

**Comment by bbockelm** [comment]
I'd do a slightly simpler version of this - randomly order the origins if there's more than one.

We have a *lot* of work to do for origin discovery - we may even need to issue a HEAD request from the director for each file for this case to see which origin or cache has the file - so I don't want to get too fancy here before we go for a big set of design work.

**Comment by bbockelm** [comment]
@haoming29 - since this is broadly in the same code as #345, I'm reassigning it to you.

**Comment by haoming29** [comment]
Looking at the code, we do a geosort for available origin servers to serve the object, so it's slightly better than picking the first in ttl cache or picking a random one, so the scope of this ticket can be changed to simply adding the metalink like we did for the cache.
