### ISSUE TITLE
Segfault on server init if `TLSCACertificateFile` exists but `TLSCAKey` does not

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#359]
I was recently testing a PR by launching a director in a mostly-fresh container and I got a segfault that originated from dereferencing the private key at [this line](https://github.com/PelicanPlatform/pelican/blob/b4759008f3fde019dd97f223b877e506d8966f45/config/init_server_creds.go#L308)

After some investigation, I **think** the problem is that `GenerateCert()` calls `GenerateCACert()` fairly early on, and if `GenerateCACert()` finds a cert file wherever it looks for one, it returns without checking if there's a corresponding key wherever `TLSCAKey` points to. Later, `GenerateCert()` makes the assumption the `TLSCAKey` exists [here](https://github.com/PelicanPlatform/pelican/blob/b4759008f3fde019dd97f223b877e506d8966f45/config/init_server_creds.go#L270C2-L270C2), but there's no guarantee of this just because the cert file was found.

This appears to have been discussed in https://github.com/PelicanPlatform/pelican/pull/167, but has now manifested in a new way.

**Comment by jhiemstrawisc** [comment]
After a bit more debugging, it looks like the issue is actually in the regular old `TLSKey` not being generated by the director. I'm going to incorporate a fix in the PR I'm working on that standardizes how the Director handles config stuff when it's served.

**Comment by haoming29** [comment]
Related issue: #256 And a PR from this issue should be able to close both.
