### ISSUE TITLE
Add `stat` functionality to director

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#367]
It's convenient to know if a given object exists in a federation.

There should be a `stat` call in the director that causes the director to contact all available origins willing to serve that object and issue a `HEAD` to see if it is actually present.  If it does exist, the response status code should indicate it and we should include the content length and checksum (if provided) in the response.

This would build on #357

**Comment by bbockelm** [comment]
Design considerations:
- For now, this is a standalone API to generic internal functionality.
- We want to query all the potential origins of an object on demand.
- We don't want to do a global thread (goroutine) pool because a single unresponsive origin can block the director functionality.  Instead, a per-origin goroutine limit is more suitable (we still want to avoid overloading the origin).  The `errgroup` [package](https://pkg.go.dev/golang.org/x/sync/errgroup) may be fairly close to what we need.
- Even with concurrency limits, we may want to still have an overall rate limit per origin.  I believe there are common packages in golang for this.
- We probably want a channel-based interface internally between the goroutines and the API.
- The internal API should control the minimum/maximum number of positive responses and the time to wait on slow servers.  Consider canceling queued queries if the maximum number of responses is hit.
   - Example: if we want to do metalink in the future, how many server responses do we wait for before returning to the client?  Do we wait for a fixed amount of time (100ms) or a minimum number of positive responses?
- How do we want to manage caching of results?  There are downsides to both positive and negative caching (especially if objects are uploaded based on a negative response).

**Comment by haoming29** [comment]
@bbockelm Speaking of the API, do we want to add it as an additional web API at the director just for testing purposes? It's very hard to test if my code works or not if I don't expose it to the outside.
