### ISSUE TITLE
Create end-to-end test for recursive downloads and uploads with xrootd

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#391]
After the functionality of these features is sound, generate a unit test for them. Waiting for Emma to fix a bug with the scitokens config and the xrootd issuer config, issue #390

**Comment by joereuss12** [comment]
This is currently stalled until Emma completes the "federation in a box". Stalled this because to test this I was calling `DoStashCPSingle()` however, on top of an origin being spun up, it requires a namespace and a director as well using this function. While I could move forward it seems redundant as we can just wait for the completion of #172

**Comment by joereuss12** [comment]
Also included recursive uploads since those cannot be unit tested either, see https://github.com/PelicanPlatform/pelican/pull/415#issuecomment-1836761538. I figure I can just test both in one go

**Comment by jhiemstrawisc** [comment]
@joereuss12 is this all finished up?

**Comment by joereuss12** [comment]
Since recursive uploads and downloads rely on topology at the moment until Emma's PR gets merged: #716, I think we should just move this to v7.6.0 to be safe. I can try to get this done tomorrow after Emma's PR is merged though.
