### ISSUE TITLE
Origin UI didn't redirect to /view/initialization/code/ at the start

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#413]
For a fresh origin, if the user spin up the origin and go to `https://<origin-host>`, the UI will be redirected to `/view/login`, which should be `/view/initialization/code/`. This can be confusing to users to start off.

We have an existing API called `/api/v1.0/origin_ui/loginInitialized` (which will be renamed to `/api/v1.0/auth/loginInitialized` when #398 is merged) that returns `{"initialized": true}` if user has finished activation flow (and setup a password) or `false` otherwise. We should use this API to redirect new user to correct login page.

**Comment by CannonLock** [comment]
This was closed by the backend redirects getting added
