### ISSUE TITLE
Pelican origins are unreachable with `pelican object copy`

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#436]
When we set up a new pelican origin, the object store should be available for download across the federation (assuming the downloader has the appropriate access token). However, due to the way origins self advertise to the director, there are no caches marked as available to serve the namespace, and `pelican object copy` will always fail because the client has no logic to check directly for an origin.

**Comment by bbockelm** [comment]
@jhiemstrawisc - I'm not sure I follow the description.  Are you saying this occurs all the time -- or only when there are no caches available?

**Comment by haoming29** [comment]
@jhiemstrawisc  In this case, can we hint the user to turn on the `Origin.EnableFallbackRead` to get it working? I'm pretty sure it will allow the local client to download a file through its local origin without a cache.

**Comment by jhiemstrawisc** [comment]
Sorry for losing this in my inbox! I've never seen `Origin.EnableFallbackRead` so I don't know the answer to your question, but the name implies to me that this would need to be configured at the origin, and this is specifically an issue between the client and the director.

When a director is responding to a client request for an object through its `object` API,  it responds to the client with a 404 if there's no cache willing to serve the object. I think the director should redirect to an origin in this case, as long as we sort out what it means for an origin to be willing to serve clients directly.

**Comment by haoming29** [comment]
> Sorry for losing this in my inbox! I've never seen `Origin.EnableFallbackRead` so I don't know the answer to your question, but the name implies to me that this would need to be configured at the origin, and this is specifically an issue between the client and the director.
> 
> When a director is responding to a client request for an object through its `object` API, it responds to the client with a 404 if there's no cache willing to serve the object. I think the director should redirect to an origin in this case, as long as we sort out what it means for an origin to be willing to serve clients directly.

Hmm. I can get the director return `307` at `object` API without a cache.

**Comment by jhiemstrawisc** [comment]
Maybe things have changed for the better since December!

**Comment by jhiemstrawisc** [comment]
Yep, it looks like this was sorted out. Thanks for looking into it 😃
