### ISSUE TITLE
Pelican container not compatible with arm

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#438]
Trying to build or work with the Pelican Docker container that comes pre-bundled with things like OA4MP and the scitokens-oauth2-server is very painful for people on ARM. In particular, trying to build the docker container on ARM immediately fails because of the line:
```
FROM hub.opensciencegrid.org/sciauth/scitokens-oauth2-server:release AS scitokens-oauth2-server
```

Do we have the ability to poke these upstream dependencies and have them built for arm as well?

**Comment by bbockelm** [comment]
Didn't we hit this before?  I see the following in `dev.Dockerfile`:

```
# We specify the platform as scitokens-oauth2-server didn't publish arm version and we don't want to
# fail on building this container on arm machine
FROM --platform=linux/amd64 hub.opensciencegrid.org/sciauth/scitokens-oauth2-server:release AS scitokens-oauth2-server
```

The files we pull from the scitokens Docker container are all Java (and hence the amd64 version is fine for all platforms).
