### ISSUE TITLE
Require Admin approval for new caches

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#439]
When a cache is added to the namespace registry, there should be a default admin setting (a JSON) that is set to false. If this evaluates to false when the director queries the registry for that cache, it will return a 404 error. This is to prevent caches being added to the federation without admin approval.

Notes:

We should ensure that advertiseOSDF still works properly as all the OSDF caches have all been approved. Also make sure we can still do end-to-end testing with a federation in a box

**Comment by turetske** [comment]
If existing (non-OSDF) caches do not have this set, assume they haven't been approved.

**Comment by haoming29** [comment]
As a note, #264 will implement this as part of the registry web-ui in7.4
