### ISSUE TITLE
Allow caches to pull from other caches

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#446]
Right now, when the director is in "origin mode", it'll only return origin endpoints to a query.

This isn't right: we should think of this as "source mode": return endpoints that can source an object.  This might include, for example, other caches (especially once #367 is tackled and the director knows potential locations for objects).

Change the director logic so it'll perform `HEAD` queries against other caches when a request for a new object comes in, cache it in memory, and potentially add a cache to the response in this case.

**Comment by haoming29** [comment]
This is blocked by the fact that the current setup of the `stat` feature only supports public namespaces as noted in the PR: https://github.com/PelicanPlatform/pelican/pull/682

We need to add the support for protected namespace first before the `stat` call returns correct result

**Comment by haoming29** [comment]
Since this is still blocked by #1093, bump this to 7.9
