### ISSUE TITLE
Namespace registration does not consider namespaces registered via Topology

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#453]
When namespace ads in the director are populated via topology, we would expect that an origin trying to register an already-registered-in-topology namespace should fail to register with the registry. However, we don't do anything to check this because the registry is completely unaware of topology (all of that code lives in the director).

I haven't checked the consequences of this, but I suspect the pelican origin will show appear in the Director as a valid origin for serving the same namespace.

**Comment by haoming29** [comment]
Another note, I remember Brian talked about this when I tried to figure out the `WebUrl` VS `Url` for `serverAd`. If we want to handle the conflict between topology and registry, we might want to consider merging the ADs from topology and registry/director.
