### ISSUE TITLE
Standardize how we use the term `Issuer`

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#479]
There are lots of places where we talk about issuers. This should be standardized with a set of well-formed utility functions that can provide information about a server's personal issuer, as well as providing information about other servers' issuers.

**Comment by haoming29** [comment]
@jhiemstrawisc Any further details about how this ticket can be done?

**Comment by jhiemstrawisc** [comment]
I think this is one that requires group discussion. Let's bring it up during a team meeting, and in the meantime I'll open a discussion on GH.

**Comment by bbockelm** [comment]
This one is really hurting due to inactivity.  Since there's not much of a concrete thing to do, I'm going to close it in lieu of Justin's proposed discussion.
