### ISSUE TITLE
In GHA, do not build all platforms on Mac OS X / Windows

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#50]
goreleaser does a cross-platform build across the GitHub action matrix.  That is, on Ubuntu, it builds for Linux, Windows, and Mac.

This is repetitive.  For the Mac and Windows platforms -- by far the slowest and the most expensive to run on -- we should just build for the local platform as all we want to do is run the integration and unit tests.

**Comment by bbockelm** [comment]
Pushing off to v7.2.0 -- too low-priority for the remainder of v7.1.0.

**Comment by Techming** [comment]
Closed with #218 merged
