### ISSUE TITLE
Bail early if we run out of disk space on the destination

### ISSUE THREAD

**Issue by matyasselmeci** [PelicanPlatform/pelican#506]
If stash_plugin is downloading multiple files and fills up the disk with one of them, it keeps going through the file list and trying the rest of the files. This is kind of inefficient -- it should just bail out early.

It would also be useful to delete any partially downloaded file(s) so we have enough room to write the output classad to report the failure.

**Comment by Todd-L-Miller** [comment]
In the relatively near future, I would prefer to preallocate space for the output ClassAd and maybe leave the disk full (so that HTCondor properly/automatically reports it), especially if the disk is full because of something else going on with the system.
