### ISSUE TITLE
Separate out multi-use parameters for use w/ pelican serve" mode

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#523]
Normally, when pelican runs a server, it is only running one per process, so server level parameters (e.g. "Server.IssuerUrl", "Server.WebPort", etc.) are only set and used once. Since "pelican serve" runs multiple servers within a process, these parameters can overwrite each other and cause issues.

We should create server type specific variables (e.g. "Director.IssuerUrl") which get their values from either being set directly OR from the server level equivalent. So the old parameter.yaml or command line inputs will still work, but this will prevent multiple servers from overwriting each others values, which is important for periodic tests and readvertisment. Ideally, this will be hidden values that rarely need to be set by the user in a parameter.yaml file.

**Comment by bbockelm** [comment]
I'd like to have the `pelican serve` mode to bend toward having all the applications hosted by the same server/port.  So, in the specific case of `Server.IssuerUrl`, it really should stay under `Server`: all the applications should have the same value.

That said, there may be other, better, examples of where server values should be split out per application.  Before starting on the implementation here, can you please enumerate the configuration keys that need to be changed so we can review/discuss?

**Comment by turetske** [comment]
@haoming29 Yeah. I agree that this can be closed.
