### ISSUE TITLE
stash_plugin should early abort on input failures

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#535]
When the plugin is downloading input files, if one file fails the job won't be able to start.  Therefore, we should stop at the first failure, produce an output file, and then exit.  This would be exceptionally helpful for cases like the NRAO where there's 350GB of inputs -- downloading another 340GB after an early failure causes debug cycles to lengthen significantly.

This is different for uploads: on failure, we still want to upload as much of the output as we can because the user may be interested in the partial result.  So the current behavior for uploads should be kept.

**Comment by matyasselmeci** [comment]
This would also take care of #506
