### ISSUE TITLE
Enumerate client error codes

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#538]
Having a structured set of error codes from the client helps us summarize and aggregate failures and provides some guidance to the user on how to correct the issue.

I propose we start a new YAML file collecting the known Pelican client error codes.  A few thoughts.

1.  It's good to group these up into major and minor codes, much like there's the 3xx, 4xx, and 5xx series of HTTP status codes.  Todd Miller did a [good writeup](https://docs.google.com/document/d/1Gbb7XDOtmLX_xcfmCwP8KAZ_s6PDDGgCamGoDl145Ww) of proposed error categories in HTCondor and those would be a good set to start with.
   * For example, if there's a major code for problems in writing out the file to local disk, the minor subcode might be the POSIX errno.
3. Design a corresponding PelicanClient error object that can wrap other errors throughout the client base.
4. For `pelican object copy` and the like, map from Pelican error code to process exit code.  The help function should document the possible exit codes; this might come from the YAML file.
5. The YAML file should have a document per known error code.  The keys should include:
   * Major / minor code values.
   * Client exit code.
   * Description.
   * Whether the error might be resolved by a retry (could be a boolean).

Before we try and implement the error code functionality, it'd be better to put together a design document trying to enumerate the errors for review.

**Comment by joereuss12** [comment]
Work in progress design doc: https://docs.google.com/document/d/1hP3tyxq1jjH3Tb9Z2M1e_OUT0IGUPfh7-AYZF_l62Ck/edit?usp=sharing
