### ISSUE TITLE
Improvements to the registry homepage

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#558]
When I first went to the registry's landing page, I got this:

<img width="1423" alt="image" src="https://github.com/PelicanPlatform/pelican/assets/1093447/06b9a170-28e4-4fb6-a842-a5c8092c8287">

It took me awhile to realize there are _two_ tables here, not one poorly-formatted one.  Add some shading or borders between the tables to draw a visual distinction.

Further, there's no explanation of what I'm looking at.  Can we add, at a minimum:
1.  A title to the page.
2. An intro paragraph or sentence about what the registry is and does.
3. A sentence below the table header describing what is being looked at.
4. Be able to sort and filter on the table contents.
5. Tooltips on the table headers describing what the column means.
6. For missing admin data or identities, some note that there is none registered (instead of a blank box).

The health widget should be on the page as well.

Someone with minimal Pelican expertise should be able to navigate to this page and, after looking at it, have a rudimentary understanding of what they're seeing.

**Comment by CannonLock** [comment]
I made some changes that should address some of this. I have created a second ticket to address the rest of the issues within the context of the new page.
