### ISSUE TITLE
Don't request new token from file transfer plugins

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#56]
The plugin when it is run should assume it is fully automated and not request any feedback.

**Comment by turetske** [comment]
@joereuss12 or @bbockelm Can I get some clarification as to what this means? Which plugin? Where is it located? Should this just remove token request/authentication from the plugin?

**Comment by bbockelm** [comment]
The "staging plugin" (https://github.com/PelicanPlatform/pelican/blob/main/cmd/plugin_stage.go) is meant to only be run by HTCondor with all the authorization pre-configured.

However, if you run the plugin, it'll run the "token acquisition" workflow which tries to read the credential configuration file (potentially asking the user to provide the decryption password).  If a decryption password is needed -- or the token isn't readily available, return an error that a credential is required but is currently missing.
