### ISSUE TITLE
Topology/Authfile generation

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#564]
In the OSDF, parts of the namespace are managed via X509 client certificates and not tokens.  The X509-based authentication is authorized via entries in the Authfile.

We consider the X509-based authentication deprecated and don't want to collect X509-based information in the Pelican registry.  However, to migrate the OSDF off the legacy packaging before these legacy authentication cases are retired (which might be quite awhile!), we will need to still support these Authfile entries.

Accordingly, when in "OSDF mode" and generating the cache's Authfile, we should query topology for additional X509-related Authfile entries and merge those authorizations in.  @matyasselmeci already has a Python-based script for performing these queries -- we just need to convert it to golang and embed into Pelican.

**Comment by matyasselmeci** [comment]
This is the script that we currently use: https://github.com/opensciencegrid/xcache/blob/V3-branch/src/authfile-update

**Comment by matyasselmeci** [comment]
By the way this issue says Authfile but OSDF caches/origins also pull their scitokens.conf from Topology. Is there another issue for doing the same generation for scitokens.conf?

**Comment by bbockelm** [comment]
The Authfile covers X509 which I don't plan to port into the core of Pelican.  It's OSDF specific and once it's not in topology, we will drop it.

For scitokens.cfg, the director should be importing info from topology and the caches ought to generate the correct info.  I believe there are some open issues along these lines - all things I'm hoping to resolve before 7.5.

**Comment by matyasselmeci** [comment]
and the cache/origin will download scitokens.cfg from the director instead of Topology? I assume it has to be on disk so xrootd-scitokens will see it...

**Comment by turetske** [comment]
Just to confirm, this task is just for the cache's Authfile, not any other configuration file from from topology.

**Comment by jhiemstrawisc** [comment]
Closed by #738
