### ISSUE TITLE
Improve the download page

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#579]
The [download page](https://docs.pelicanplatform.org/install) stinks.  There's a long list of different types and the poor user needs to read through them all to figure out what they need.  Worse -- there's not even a direct download link!

Instead, let's take some ideas from https://www.downloadkubernetes.com/.  Have users select their OS of choice through a multi-choice button, then present to them the most common option (latest binary version on the most popular platform for that OS; e.g., arm64 for Mac, amd64 for Linux).  After the suggested link, provide a table where they have additional selectors for architectures (default to the most common one) and version.  The rows of the table should be the different formats.

Since we build nightly, it should be possible to generate the list of releases and the direct download links.

**Comment by CannonLock** [comment]
@Rhymlore Some small design tweaks. 

Preselect one value on each bar to make the table smaller. Keep the other download content just below this table, but make sure the numbers are dynamic to the latest release if any are currently hardcoded. 


Do the last three minor releases from the api: 7.4.0, 7.3.3, 7.5.x.

**Comment by joereuss12** [comment]
> @joereuss12 Can you comment on the files in this release? What should Alperen have available for download and how should I segment them?

Do you still need my input for the files in the release? To be honest, I'm not entirely sure what the new packages listed are for/when they were even added, they just got pulled for the release. 

If you need my help though I can do some digging/poking for you to figure out why they were added and what they are for. You should at least be able to get the os, aarch, and version from them they are named nicely

**Comment by CannonLock** [comment]
This ticket is closed, @Rhymlore is working on follow up comments
