### ISSUE TITLE
Require federation token for accessing Prometheus metrics

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#6]
The federation should be posting a JWKS as part of its auto-discovery protocol.

Since some of the per-directory monitoring data might be sensitive, we should require a signed token from the federation to access the prometheus monitoring.

**Comment by turetske** [comment]
Metrics API in the metrics subdirectory. Connects prometheus to the web-server. All the metrics are public, we want to move the metrics to be private. 

1. origin_ui handler to validate the cookie, needs the cookie to access the metrics.

2. what should the token based access for external users should look like.
