### ISSUE TITLE
Longer refresh interval for initial code authentication

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#603]
Our initialization code has a really short time to live, for 30s. It happened to me several times where I started Pelican server in a fresh container and was directed to login page, trying to figure out the host name/urls/https handshake error for my host machine, and by the time I was ready to type, I got "invalid initialization code" error and realized there's a new code generated when I look at the log messages.

Can we extend the expire time of the code from 30s to 1 minute or 5 minutes? This way the admin user will have significantly lower chance of missing the old code. We might also want to add notes on the initialization code UI page reminding users that the code _will_ expire and gets refreshed.

**Comment by bbockelm** [comment]
Supposedly (and not sure we have a test for this?) you can enter either the last or previous code and have them be valid.  That means the time to live should be about a minute already.

So, perhaps this is a bug?  I would be fine extending this to the last 2 codes (for up to 3 valid codes total).

**Comment by haoming29** [comment]
@bbockelm Yes you are right, one can use two latest one-time code to login, and if the server is started in a fresh container (without `-d` flag), it's pretty clear of what the password is, so I won't worry user to skim through log messages to find one. Close the issue accordingly.
