### ISSUE TITLE
Caches log sensitive information

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#604]
The cache is currently logging access JWTs whenever it receives a request for a resource with the token embedded in the URL or in an authorization header. This may be a side effect of the Director's forwarding behavior, where any bearer tokens are parsed and passed via the `authz` url parameter for the redirect. 

IIRC, we initially chose this kind of URL-encoding route for tokens to work around the fact that most HTTP clients drop `Authorization` headers on a redirect for security reasons. However, if tokens are also logged when sent via header, the solution isn't as simple as switching the token passing.

My guess is that origins are also logging these values, but we haven't observed that yet.

Whatever the fix may be, we should figure out how to avoid logging this kind of information.

**Comment by matyasselmeci** [comment]
Looks like XrdHttp is logging every header line as well as the first request line around this block of code: https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpProtocol.cc#L592-L614

We should request the xrootd developers that they change XrdHttp to censor the "Authorization" header and the "authz" argument in their logs. Until then, we should remove `http.trace all` from the generated xrootd configs.

**Comment by bbockelm** [comment]
Indeed - we don't want to have `http.trace all` set as a matter of course.  If nothing else, it's also an overwhelming amount of debug information and not usable on production-scale caches.

(This relates to my comment earlier this morning about having some fine-grained controls on log levels.  Someone may want to turn on debugging for the web server but not want to dump every header line ever encountered.)

**Comment by haoming29** [comment]
Do we effectively solved this issue with #605 merged in? @jhiemstrawisc @matyasselmeci

**Comment by jhiemstrawisc** [comment]
Yep!
