### ISSUE TITLE
Feedback on service registration

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#636]
Here's the page I see as an administrator:

<img width="943" alt="image" src="https://github.com/PelicanPlatform/pelican/assets/1093447/0dd1f730-5c5a-4653-9578-d0b46529573f">

Thoughts:
1.  We should have the service type be a dropdown (origin, cache, namespace).  Right now, we only have a namespace and cache, of course.
2. The note about caches starting with /cache in the namespace is confusing and internal.  When a cache is selected, just ask for a hostname.
3. Should have some better behavior when no institutions exist.
4. For "Pubkey is your origin's public JWKS. It must in JSON format, not JSON string".  I don't know what the second sentence means.  For the first sentence -- I think the important question is how does one find this out?  What command should I run?
5. Similarly for "Security Contact ID" -> how do I figure this out?  What happens if I'm not using CILogon?
6. As noted elsewhere, having a sentence up top on what this form is doing would be immensely helpful.

**Comment by CannonLock** [comment]
@bbockelm 

1. Sounds good.
2. Agree and Disagree on this one. I think it would be confusing to have them enter one prefix and have the form submit a generated one. I propose that on type selection of cache the prefix gets populated with the /cache prefix. Maybe need a conversation on what is OSDF specific and what isn't though.
3. Agreed, but something else should yell at them well in advance of them hitting this form if they are missing a required field. 
4. Will fix. 
5. I am unsure the best way to find this, ideas on who to ask about this?
6. Will Fix.

**Comment by haoming29** [comment]
For 5, I'd suggest we create a new doc page for `Register a namespace via Web UI` and link to the section where we can detail what this means and where to find the value. Similarly to other fields that require more than one line of explaination.
