### ISSUE TITLE
build and publish action no longer installs pelican

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#64]
It looks like the build and publish GHA no longer runs goreleaser to provide the container with a runnable copy of pelican. If pods running on Tiger update to these new containers, it will break the development instances of the central services we currently have running.

**Comment by bbockelm** [comment]
After discussion, we noticed the build has been moved into the Dockerfile itself; that should still result in a working binary.

That said, if in testing a problem shows up, please re-open.
