### ISSUE TITLE
Xrootd not properly shutting down on test failure

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#644]
When writing end-to-end tests with xrootd, I noticed that xrootd leaves a process running on test failure. Below is the process that is kept running on port 8443:
`xrootd -s /tmp/XRootD-Test_Origin2970414796/xrootd.pid -c /tmp/XRootD-Test_Origin2970414796/xrootd.cfg`

This causes me to have to manually kill the process when the leaky process should be closed on failures.

**Comment by haoming29** [comment]
After a conversation with @joereuss12, we figured that if in the test, the program calls `os.Exit()` no matter intentionally or not, the clean-up function to shut down various server component including xrootd will not get a chance to execute and thus causing dangling daemons and memory leak. If we do need to test with program calls to `os.Exit()` we should follow the way we test the different alias for our executable: https://github.com/PelicanPlatform/pelican/blob/3caae35f06cd96ae97c2afca51a470b98c060010/cmd/main_test.go#L154 by building a binary and execute the binary directly in hope to get the desired result. Not the best way to do it but should give a good work around.

**Comment by haoming29** [comment]
Since the issue wasn't from the code, will close the issue unless we found another cause of the issue
