### ISSUE TITLE
Add a place where you can find the version number

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#652]
I am currently thinking a (?) on the bottom left of the page.

**Comment by haoming29** [comment]
I mean if the only thing we display is `v7.4.0` then it should be able to fit into the width of the tab

**Comment by CannonLock** [comment]
@haoming29 Any idea on how I can get the version via api or something?

**Comment by CannonLock** [comment]
@haoming29 Okay, if your solution is going to be at all manual I can also read the package.json files version and have it track the pelican version.

**Comment by haoming29** [comment]
@CannonLock That also works. If the version in package.json is in-sync with the git tag then that should work.

**Comment by CannonLock** [comment]
@haoming29 Cool lets do that, seems the most natural to me. Not sure how you would handle this otherwise.

**Comment by haoming29** [comment]
Closed by #722
