### ISSUE TITLE
Allow multiple cache instances to register if they run on different ports

### ISSUE THREAD

**Issue by matyasselmeci** [PelicanPlatform/pelican#662]
xcache-based osdf caches have two instances running: an unauthenticated instance (on port 8000) and an authenticated instance (on port 8443). When I try to do the same thing using Pelican, I get the following error from one of the instances:

> Failed to register with namespace service: Failed to register prefix /caches/CHTC_STASHCACHE_CACHE: Failed to make request: server encountered an error during key-sign challenge commit failed: The prefix already is registered

Perhaps include the port number in the prefix that gets registered? `/caches/CHTC_STASHCACHE_CACHE:8000` ?

**Comment by haoming29** [comment]
Mark as closed with the conversation we had with @bbockelm
