### ISSUE TITLE
Cache: add support for throttling plugin

### ISSUE THREAD

**Issue by matyasselmeci** [PelicanPlatform/pelican#666]
@bbockelm wrote a plugin for XRootD that can throttle the number of connections; it is useful for keeping underpowered caches from falling over.  It is included with the XRootD RPM but is documented here: <https://twiki.cern.ch/twiki/bin/view/Main/XrootdThrottlingExperimental>.

It should be disabled by default but it would be helpful to allow enabling it and setting the concurrency. The syntax is:
```
xrootd.fslib throttle default
throttle.throttle concurrency CONCURRENCY
```
omit both lines if the plugin is disabled.  It can also cap IO ops per second and max transfer speed per client but according to the doc, concurrency is the most useful option so supporting that should be enough.

**Comment by turetske** [comment]
@matyasselmeci  @bbockelm Is there a default concurrency we want to allow? Say if the user enables the plugin but doesn't set a concurrency?

**Comment by matyasselmeci** [comment]
I suggest having just one knob that sets the concurrency, and if it's non-null then enable the plugin.

**Comment by matyasselmeci** [comment]
My top 3 suggestions for knob names:
1. Cache.MaxConnections
2. Cache.MaxConcurrency
3. Cache.Concurrency

@bbockelm , which of these seems like the best (or do you have another suggestion)?

**Comment by bbockelm** [comment]
I do think I'm going to grab this for a bit and probably switch to `MaxConcurrency` since we'll want to use `concurrency` for a prometheus metric of the current concurrency level
