### ISSUE TITLE
Allow changing registration retry delay

### ISSUE THREAD

**Issue by matyasselmeci** [PelicanPlatform/pelican#668]
If my cache or origin fails to register with the namespace service, I would like to retry (much) less frequently than every 10 seconds because otherwise it is just noise in the logs.

**Comment by haoming29** [comment]
This sounds like a bug. The advertisement is intended to be executed per 1 min no matter it succeeded or not. Could you confirm this is within 1 min? @matyasselmeci

**Comment by haoming29** [comment]
You are right. I mismatched it with the director advertisement
