### ISSUE TITLE
Pelican in production Docker image has the wrong version number

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#681]
From @brianhlin, if you run the version command inside the production Docker container, you'll get:

```console
[root@hostname pelican]# ./osdf-client --version
Version: 7.4.1-next
Build Date: 2024-01-10T22:48:53Z
Build Commit: 3caae35f06cd96ae97c2afca51a470b98c060010
Built By: goreleaser
```

while the tag this container was built for was `7.4.0`.

This is because we use `--snapshot` flag when running goreleaser in the production image build. We should remove this flag to ensure the version matches git tag for production build.

**Comment by williamnswanson** [comment]
It seems that there was something wrong with my fix, as this issue still exists in the 7.5.4 container:

```
sh-4.4# ./osdf-client --version
Version: 7.5.5-next
Build Date: 2024-02-09T14:45:28Z
Build Commit: 71053e4b6852a7eda4422131d06fffcf8b0e981f
Built By: goreleaser
```

**Comment by brianhlin** [comment]
@haoming29 what's the Pelican dev policy for closing issues that have been fixed in `main`? Should they be closed as PRs are merged or do we leave the issues open until there's been a release with the fix?

**Comment by haoming29** [comment]
> @haoming29 what's the Pelican dev policy for closing issues that have been fixed in `main`? Should they be closed as PRs are merged or do we leave the issues open until there's been a release with the fix?

We link the issue with the PR, so it closes when the PR is merged in. This one is special because we re-opened it after the initial fix, but I think we should be good to close this one now.
