### ISSUE TITLE
Create and link a container to all PRs

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#690]
Create a container ( and a fitting retention policy ) so that each PR publishes a container so that we can easily run the new Pelican build. 

Sample PR text:

> Container built for this branch at hub.opensciencegrid.org/pelican_platform/pelican:<branch-name>!
> 
> Replace <your-command-here> to test this PR's content.
> 
> ```
> docker run --rm -it -p 8444:8444 hub.opensciencegrid.org/pelican_platform/pelican:<branch-name> <your-command-here>
> ```

**Comment by jhiemstrawisc** [comment]
@CannonLock I think this can be closed, no?
