### ISSUE TITLE
Force pre-declaration of the parameters in the documentation

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#71]
Write a go generator that will take the contents of `docs/parameters.yaml` and turn them into an enum.  Remove direct access to `viper.Get*` and provide a wrapper in the config language that accepts only the enum type as input.

**Comment by turetske** [comment]
1. Look at go generator and write a small program to create the corresponding go structs. 

2. Remove direct access to viper.Get, convert call sites and make it type safe. For remaining add a follow up ticket.
