### ISSUE TITLE
Add rate limiting to various login endpoint

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#711]

**Comment by CannonLock** [comment]
This can also be solved by using NGINX to reverse proxy the websites, maybe we can create a blessed image that deploys the website like so?

**Comment by haoming29** [comment]
> This can also be solved by using NGINX to reverse proxy the websites, maybe we can create a blessed image that deploys the website like so?

@bbockelm suggests doing it in Go as Go has a good support for built-in rate limiting functions so we don't have to add extra overhead, although I need to confirm how we can use them. But NGINX looks good to me as the long-term path to go.

**Comment by CannonLock** [comment]
Ah slick, that sounds good to me.
