### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#74]
Once we have an initial release of Pelican, we should buckle down and start writing good unit tests for all of our additions. The recent churn in the push to implement new features has at times broken other features. If we can catch this before merging through the use of a testing regimen, we'll spend less time debugging overall.

**Comment by bbockelm** [comment]
@jhiemstrawisc - I think I'm going to close this out as I created a cross-cutting project for unit tests:

https://github.com/orgs/PelicanPlatform/projects/1/views/1

Basically, it's tough to see when a "write good unit tests" issue is done.  What singular PR will close out this issue?  I think an important long-term goal like this fits the "project" better.

You'll see I started writing down a few concrete issues and attached them to the project as examples.
