### ISSUE TITLE
Add html anchor element to first-level class on parameters page

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#767]
For example, we already had anchor elements to the individual parameters, but not for the top-level class like `Transport` / `Cache`. It would be convenient if we can have it.

<img width="878" alt="Screenshot 2024-02-06 at 9 02 46 AM" src="https://github.com/PelicanPlatform/pelican/assets/41393704/d6146f1b-ad69-468c-b28b-661df48a1798">

**Comment by SayaliNilangekar** [comment]
Hello! I would like to contribute to fixing this. Is this already in progress?

**Comment by haoming29** [comment]
> Hello! I would like to contribute to fixing this. Is this already in progress?

Nope. Feel free poking around and get yourself started! Thanks for taking care of this.

**Comment by haoming29** [comment]
@SayaliNilangekar Hey Sayali. What's the status on this issue? I'm wondering if we can get this out before 7.6

**Comment by haoming29** [comment]
This is partially done (with issues) in the docs repo. Will open separate issue in docs repo for fixing errors
