### ISSUE TITLE
Prometheus token not renewed

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#787]
Pelican Services:
- [X] Origin
- [X] Cache

After my director was running for an hour or so, I started seeing messages like this in the logs of my origin and cache:

```
DEBUG[2024-02-07T20:15:33-06:00] Token validation failed with server issuer: Invalid JWT: "exp" not satisfied 
INFO[2024-02-07T20:15:33-06:00] Authentication failed. Didn't pass the chain of checking:
Token validation failed with federation issuer:  "exp" not satisfied
Token validation failed with server issuer:  Invalid JWT: "exp" not satisfied 
INFO[2024-02-07T20:15:33-06:00] Served Request                                client=192.168.0.12 daemon=gin fields.time="875.167µs" method=GET resource=/metrics status=403
```

Seeing that it's the `/metrics` endpoint, I'm guessing the Prometheus token isn't being periodically renewed.

**Comment by haoming29** [comment]
How did you run the services? I can only reproduce the issue for once, but I didn't recall there's a specific setting I changed to cause the bug, and I can reproduce the issue afterwards.
