### ISSUE TITLE
OSG xrootd build in the ARM container

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#796]
We've been bit by using the OSG build of xrootd in x86_64 and EPEL in ARM in development environments.  The former gets patches as we hit issues that, sometimes, developers "re-discover" when they use the EPEL build.

For the ARM container, let's do a `rpmbuild` rebuild of xrootd from the OSG's SRPM.  The dependencies are all in EPEL, so it really should be a single package we need to compile.

The GitHub Action-based build hosts are x86 but, in HTCondor, we've had good luck doing QEMU-based emulation on x86 for this.  Some random-but-relevant links toward this:
- [Setup QEMU action for GitHub runners](https://github.com/docker/setup-qemu-action)
- [Docker's instructions on doing ARM64 builds on GHA](https://docs.docker.com/build/ci/github-actions/multi-platform/)

**Comment by matyasselmeci** [comment]
See #806 for an initial PR.
