### ISSUE TITLE
Mark failure to get metadata response as retryable.

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#809]
Pelican Version: v7.5.1

Observed multiple failures with the following error message:

> Error: Attempt #1: Problem initializing the Pelican Client configuration: Failure when doing federation metadata lookup to https://osg-htc.org/.well-known/pelican-configuration: Get "https://osg-htc.org/.well-known/pelican-configuration": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (5s since start) ( URL file =  )|

This occurs when the client (a) can successfully TCP and TLS connect to the server but (b) never gets a response during metadata discovery.

Please add just this case to the list of retryable failures.

Since this was observed by a user, please backport to the 7.5.x series.

**Comment by joereuss12** [comment]
@bbockelm Looks like the error is already marked retryable but the plugin never did anything about this. Fixing this now!
