### ISSUE TITLE
Test director registration

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#81]
Add a unit test for the director registration API.

Test should:
- Create keypair and corresponding and token allowing registration access.
- Inject the keypair into the internal key cache.  This may require some refactoring of the key cache to be an interface so we can replace the lookup into the namespace registry with the pubkey newly-created for the test.
- Invoke the registration endpoint, check for resulting HTTP status code.
- Do the above step again with an invalid token.
- Query the director for an object within the new origin's namespace.  Ensure the response includes the newly registered origin.

**Comment by turetske** [comment]
@bbockelm I'm working on this now, but I realized this isn't quite clear (at least to a newbie) on what exact API functions is this supposed to be testing? Which module is the director registration API? I just want to make sure I don't bypass what I'm actually supposed to be writing the test for in the interest in making the test as small and focused as possible.
