### ISSUE TITLE
Make login/logout dynamic based on user state

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#836]
Pelican Version:
_Run `./pelican --version` to get version number._

Pelican Service:
- [X] All

**Describe the bug**
_A clear and concise description of what the bug is._

When you are the the director or registry there is a button to logout no matter the users state. Lets make this check if the user is logged in before displaying this button.
Additionally if there is an error on this button the pop up is too quick so lets fix that as well.

**Comment by haoming29** [comment]
@CannonLock As I recalled, this should be fixed with a PR for #631 ,right?
