### ISSUE TITLE
Add code coverage metrics

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#85]
Our unit test coverage is pretty lousy.  As we're improving it, however, it's good to have metrics about how we progress.

Investigate how to best do code coverage in go projects so we can start measuring progress as we try to expand our unit test suite.

**Comment by turetske** [comment]
Go actually has built in functionality for this (as of last January, I think).

If you just want to look at package coverage, run `go test -cover ./...`

If you want to go more in depth, you can get total code coverage by running the following from the pelican directory:

`go test -v -coverpkg=./... -coverprofile=cover.cov ./...`

Followed by: `go tool cover -func cover.cov` Which will give individual function coverage plus total coverage (15.4% at time of this comment)

If you want a fun interactive tool that will highlight what is and isn't covered by the unit tests, you can run:

`go tool cover -html cover.cov`

Note that <cover.cov> can be named anything you choose in the above examples
