### ISSUE TITLE
Markdown links in configuration parameters documentation aren't rendered

### ISSUE THREAD

**Issue by brianhlin** [PelicanPlatform/pelican#864]
In https://docs.pelicanplatform.org/parameters, I see quite a few links that look like:

```
[here](https://dev.maxmind.com/geoip/docs/databases/city-and-country)
```

Looks like whatever Markdown engine we're using isn't properly rendering them as links.

**Comment by brianhlin** [comment]
@CannonLock I'm assuming this is in your court?

**Comment by haoming29** [comment]
@brianhlin This is a duplicated issue as in #763
