### ISSUE TITLE
Leak of xrootd/cmsd processes

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#868]
Pelican Version: 7.5.7

Pelican Service: Origin (probably cache too)

**Describe the bug**
When @brianhlin and @biozit were installing the Pelican origin, both encountered issues with xrootd process leaks.

That is, after an initial failure in startup, the xrootd process was not killed.  Subsequent restarts of pelican from within the same container would then rapidly fail as the new xrootd process was unable to bind to the new port.

**To Reproduce**
@biozit's problem occurred when port 8444 was firewalled off.  This caused the startup health check to fail, the server to shutdown, and xrootd to remain lingering.

Here's a patch that creates an error at the same point in the startup:
```
--- a/launchers/launcher.go
+++ b/launchers/launcher.go
@@ -22,7 +22,6 @@ import (
        "context"
        "fmt"
        "net"
-       "net/http"
        "os"
        "os/signal"
        "syscall"
@@ -192,11 +191,13 @@ func LaunchModules(ctx context.Context, modules config.ServerType) (context.Canc
                shutdownCancel()
                return nil
        })
-
+/*
        if err = server_utils.WaitUntilWorking(ctx, "GET", param.Server_ExternalWebUrl.GetString()+"/api/v1.0/health", "Web UI", http.StatusOK); err != nil {
                log.Errorln("Web engine startup appears to have failed:", err)
                return shutdownCancel, err
        }
+*/
+       return shutdownCancel, errors.New("test shutdown")
 
        if modules.IsEnabled(config.OriginType) {
                log.Debug("Finishing origin server configuration")
```

Run a origin with this setup.  It should crash nearly immediately and you'll notice an xrootd process still running afterward.

**Comment by biozit** [comment]
@bbockelm, thank you for reporting it
