### ISSUE TITLE
Prometheus monitoring for the g-stream 

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#873]
Pelican Service: Cache, Origin

In https://github.com/xrootd/xrootd/pull/2206, there are new monitoring statistics added for measuring the overall I/O load on an origin or cache.  Once/if that work gets merged, let's add a corresponding Prometheus metric.

Goal is to have the I/O load eventually be part of the cache and origin selection logic alongside GeoIP.

**Comment by haoming29** [comment]
Move to 7.8 as OSG build of xrootd can't be released before 7.7 release.

**Comment by haoming29** [comment]
Waiting for a new RPM to be build by @matyasselmeci or Xrootd 5.7.0 release; otherwise the plumbing work is done in my local branch. Given that the v7.8 release is today (5/2), I'm not sure if we can include this in v7.8.0 release

**Comment by haoming29** [comment]
The new RPM is out yesterday and I was able to test it with the rest of the pipeline and it works. I will finish up installing the patch RPM in various containers today and hopefully get the PR out later today.
