### ISSUE TITLE
Fix published container so that supervisor can run as user `xrootd`

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#90]
Deployments on Tiger quit serving the director. After investigating, it looks like the switch to default to user `xrootd` in the published container is causing permissions issues with `supervisord`. When the container tries to launch the entrypoint script, `supervisord -c /etc/supervisord.conf` fails because it sets the log (and other outputs) to places in `/var` that the user doesn't have permissions to write to.

I'm not sure which approach we should take -- a) get `supervisord` running as root, b) have it run as the `xrootd` user and adjust file permissions so that it can write to `/var/log/supervisord` or c) run `supervisord` with user `xrootd` and have those misc files written to someplace the user already has permissions to write to.

**Comment by bbockelm** [comment]
I'm leaning toward reverting the change ... there's a number of things to consider here (for example, the container may _need_ to be privileged if it's running a multi-user origin!) that simply "fixing it" to run as xrootd won't suffice.
