### ISSUE TITLE
Standardize JSON responses

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#900]
When responding to HTTP requests, we have a few different JSON responses indicating success. These include:
```
{"msg": "success"}
{"message": "success"}
{"status": "success"}
```

and maybe more that I don't know about. This was also discussed in PR #877.

We should clean this up. That I'm aware of, there isn't a widely-accepted standard here, so as long as we're consistent, I think whichever we settle on is OK.

**Comment by haoming29** [comment]
In #884 Brian added [a struct](https://github.com/PelicanPlatform/pelican/blob/main/common/api_resp.go) in `common` package that can serve as the basis for this PR
