### ISSUE TITLE
Public origins need `sec.protbind * none` for legacy compat

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#906]
Pelican Version:
_Run `./pelican --version` to get version number._

Pelican Service:
- [x] Origin

**Describe the bug**
When origins are served in public mode, the origin should also support the xroot protocol for compatibility with legacy caches.

This can be accomplished by adding `sec.protbind * none` to the config.

**Comment by haoming29** [comment]
It seems that this issue has been fixed by @jhiemstrawisc in #907. Close the issue

**Comment by bbockelm** [comment]
@haoming29 - thanks for closing the issue!  However, in the future, please make sure to link the PR that resolved the issue with the issue itself (look for the "Development" portion of the right-hand side pane).  This gets our metadata correct and may be useful for future metrics.
