### ISSUE TITLE
Servers shouldn't use `Server_ExternalWebUrl` to check process startup

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#916]
We have a smattering of checks that do something like
```
if err = server_utils.WaitUntilWorking(ctx, "GET", param.Server_ExternalWebUrl.GetString()+"/api/v1.0/health", "Web UI", http.StatusOK); err != nil {
```

The issue with this is that we calculate the external web URL with the port a service is running on, and that may not always be the port the external hostname is using. This is especially problematic with kubernetes deployments where the service is running on port 8443 inside the pod, but is externally discoverable at 443. In this case, wait until working will hit the wrong port and never succeed.

We could either switch these wait until working conditionals to use localhost, or we could break things apart so that the external web url can actually be made aware of the port the service is discoverable on from outside. I think the former is a cleaner fix.

**Comment by bbockelm** [comment]
Actually, I think the current behavior is approximately correct.

The intent is to pause the process until the external port is hooked up.  If there is a mismatch between the internal and external ports, that's fine but you'll then need to manually set the external address.  We shouldn't be overriding the provided external address.

**Comment by haoming29** [comment]
How do we want to navigate for this issue? Sounds like it's an expected behavior for Pelican. If that's the case, do we want to document somewhere on how to set the correct param to make the check work in production?

**Comment by jhiemstrawisc** [comment]
It almost feels like we need to start thinking about how to document containerized server deployments. This won't be an issue for anyone running a server on bare metal, but there are enough differences between that and what we do in K8s that it might be nice to document the latter.

**Comment by jhiemstrawisc** [comment]
@williamnswanson @brianhlin I wanted to get your opinions on this. Can one or both of you take a look at what we currently have for containerized Pelican documentation (https://docs.pelicanplatform.org/install/docker) and suggest any edits based on the way the two of you do things? I guess running Pelican in a container isn't quite the same as running it in a K8s cluster, but there's probably a decent amount of overlap.

**Comment by jhiemstrawisc** [comment]
Reassigning this to you, @haoming29, since you're currently working on the section of docs that should cover this behavior.
