### ISSUE TITLE
ITB team reports wrong xrootd in production container

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#917]
Our integration team is reporting that they have to manually install the correct version of XRootD in our production container so that `pelican://`-style urls are recognized by xrootd. This throws a wrench in their ability to automatically deploy Pelican origins and caches. 

 @williamnswanson reports that he's able to get the required version of xrootd by running 
```
yum install -y https://repo.opensciencegrid.org/osg/23-main/osg-23-main-el8-release-latest.rpm && yum install -y xrdcl-pelican --enablerepo=osg-testing && yum update -y xrdcl-pelican '*xrootd*' --enablerepo=osg-testing
```
from within the container.

**Comment by haoming29** [comment]
@matyasselmeci Could you confirm the command above should be used in the production container? I saw there is flag `--enablerepo=osg-testing` and I'm not sure if we want to include that in production container. I can do a quick patch once we figured this out.

**Comment by matyasselmeci** [comment]
I don't think --enablerepo=osg-testing should be in the production container.  My recommendation is to just add `yum install -y https://repo.opensciencegrid.org/osg/23-main/osg-23-main-el8-release-latest.rpm` before you install any other RPMs.
