### ISSUE TITLE
Enable OAuth for origin

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#928]
We have OAuth as an option for the registry and we want to enable the same feature for the origin as well

**Comment by haoming29** [comment]
@bbockelm It seems like Globus does not support device auth flow: https://docs.globus.org/api/auth/reference/#obtaining_authorization_supported_oauth2_grant_types So the registry may be unable to use it as the auth server. Do you want us to integrate Globus for the origin only?

**Comment by bbockelm** [comment]
That is unfortunate - yes, let's keep it for web-only workflows then.
