### ISSUE TITLE
Golang-ci lint action fails with "Cannot open: file exists" error

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#929]
Pelican Version:
v7.5 (has been happening for a while though)

Pelican Service:
- [X] Other (please give the detail): Github Actions

When pushing a commit the GHA golang-ci linter sometimes gives the error: `Cannot open: file exists` for some of our packages:
```
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.12.0/cmd/build-oss-fuzz-corpus/main.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.12.0/cmd/testaws/main.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.12.0/cmd/testentauth/main.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.12.0/cmd/godriver-benchmark/main.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.12.0/cmd/testatlas/main.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.mongodb.org/mongo-driver@v1.12.0/cmd/testkms/main.go: Cannot open: File exists
```

This is usually solved by going into the Github actions' cache, and manually clearing all of them for golang-ci lint. This requires some investigation or just the removal of caching the linter step.

**Comment by haoming29** [comment]
Related: https://github.com/golangci/golangci-lint-action/issues/135
