### ISSUE TITLE
More robust discovery endpoint at the director

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#934]
According to @brianhlin , the federation discovery endpoint that the director serves has a couple of issues:
* It didn't check the url passed to `Federation.RegistryUrl` and `Federation.DirectorUrl`
* `Server.ExternalWebUrl` overwrites `Federation.DirectorUrl` no matter `Federation.DirectorUrl` is set or not

**Comment by bbockelm** [comment]
We should also aim to clean up the resulting URLs: default to HTTPS if not set; if HTTPS is used with port 443, then we don't need to provide the `:443`.
