### ISSUE TITLE
Fix Flaky Tests

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#941]
There are a few tests that intermittently fail enough to be quite annoying.

Specifically, in the director, the namespace token validation can fail.

On macOS, the recursive downloads/uploads have an intermittent failure with a header timeout.

**Comment by haoming29** [comment]
@turetske I would assume this is fixed as we disabled the related tests for macOS?

**Comment by CannonLock** [comment]
Should I open another ticket for that ubuntu test failures that have been plaguing us? https://github.com/PelicanPlatform/pelican/actions/runs/8574340084

**Comment by haoming29** [comment]
> Should I open another ticket for that ubuntu test failures that have been plaguing us? https://github.com/PelicanPlatform/pelican/actions/runs/8574340084

I think this one was a new one and was introduced by #1058 but the failure seems to be intended, unless our timeout config wasn't properly read (it was set to 10s for response header)

**Comment by CannonLock** [comment]
@haoming29 Since you know the problem more intimately can you create the ticket? It hurts me to merge with a broken test.

**Comment by haoming29** [comment]
Sure thing!

**Comment by haoming29** [comment]
I'm not sure the fix though. The topology really needs to be tuned up
