### ISSUE TITLE
Pelican fails to start on the first attempt when using TLS certificates with an RSA key

### ISSUE THREAD

**Issue by brianhlin** [PelicanPlatform/pelican#956]
Pelican Version:

```
[root@itb-osdf-pelican-origin-54b4c6c989-bhr8f pelican]# ./osdf --version
Version: dev
Build Date: 2024-03-15T17:55:45Z
Build Commit: d360e742e39c9e9d5dd928cb271464c87c159c68
Built By: goreleaser
```

Pelican Service:
- [ ] Client
- [ ] Plugin
- [X] Registry
- [X] Director
- [X] Origin
- [X] Cache
- [ ] Other (please give the detail)

@williamnswanson and I have definitely seen this issue on the registry and origin and I suspect that this is also a problem for the director and registry.

**Describe the bug**

With an RSA key in `Server.TLSKey`, the `serve` commands will fail:

```
# file tls.key
tls.key: PEM RSA private key
# ./osdf origin serve
Logging.LogLocation is set to /var/log/pelican/pelican.log. All logs are redirected to the log file.
Error: Failure when configuring the server: Private key file, /etc/pelican/cert-orig/tls.key, contains no private key
```

However, subsequent attempts to start the origin appear to succeed. Perhaps related, the TLS CA and key are generated on the initial attempt.

**To Reproduce**

1. Create a TLS cert and RSA key pair and place them in the `Server.TLSCertificate` and `Server.TLSKey` locations
1. Do not create TLS CA files
1. Run `./osdf origin serve`

**Expected behavior**

I expect the Pelican server to start on the first try with an RSA TLS key

**Comment by bbockelm** [comment]
When solving this, please add a unit test!

@brianhlin - that said, note the TLS CA is now required in order to make the connection broker work (though technically only required for the cache).  It's just that it doesn't need to be persisted between restarts nor should it interfere with the host-provided key.
