### ISSUE TITLE
Improve S3 parameter documentation

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#957]
The current S3 parameter documentation is literal and unhelpful.  For example:

```
name: Origin.S3ServiceUrl
description: >-
  The S3 service URL to be used by the XRootD plugin.
type: string
default: none
components: ["origin"]
```

Think of an admin who has never seen Pelican before.  Some questions/comments they might have:
- It says "S3 service URL" which is pretty much just the name of the option (akin to giving the definition of "a HTTPS server is a server that serves HTTPS").
- What's an XRootD plugin?  We shouldn't assume the user knows anything about XRootD or plugins.
- What's an example configuration?
- Is this required?

All the S3 parameters could use the same level of review.

**Comment by jhiemstrawisc** [comment]
This was completed in #1045
