### ISSUE TITLE
Have Pelican client advertise timeout to cache

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#997]
Pelican Service:
- [X] Client
- [X] Plugin

Have the pelican client advertise to the cache its desired timeout. We can use the configurable ResponseHeaderTimeout as the specified timeout of 10s. This way the cache can know the timeout we have right away and can take action. This won't do much right away but will set up more in the future.

**Comment by bbockelm** [comment]
We already use the header name `X-Pelican-Timeout` for managing the broker timeout.  In that case, we take a `time.Duration` and serialize it to string using the `String()` method.  [Example](https://github.com/PelicanPlatform/pelican/blob/e60b5d37f6ddc40869d09bbcefd7875fe8518ae8/broker/client.go#L406).  Let's use the same header name here.
